In [1]:
import pandas as pd
import numpy as np

In [2]:
DATA_PATH = "../data/processed/null_handled_columns_dropped.csv"

df = pd.read_csv(
    DATA_PATH,
    low_memory=False
)

print("Dataset loaded successfully!")
print("Shape:", df.shape)
print("\nColumns:")
print(df.columns.tolist())

Dataset loaded successfully!
Shape: (156985, 9)

Columns:
['Restaurant_ID', 'Facility Type', 'Risk', 'Address', 'Inspection Date', 'Inspection Type', 'Results', 'Violations', 'Location']

In [3]:
print("Unique Restaurant_IDs:", df["Restaurant_ID"].nunique())
print("Missing Restaurant_IDs:", df["Restaurant_ID"].isna().sum())
print("Restaurant_ID = 0:", (df["Restaurant_ID"] == 0).sum())

print("\nRestaurant_ID data type:")
print(df["Restaurant_ID"].dtype)

print("\nSample Restaurant_ID values:")
print(df["Restaurant_ID"].head(20).tolist())

Unique Restaurant_IDs: 22291
Missing Restaurant_IDs: 0
Restaurant_ID = 0: 0

Restaurant_ID data type:
float64

Sample Restaurant_ID values:
[2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 9.0, 9.0, 9.0, 9.0, 9.0]

In [4]:
id_address_counts = (
    df.groupby("Restaurant_ID")["Address"]
      .nunique()
)

print("Restaurant_IDs with exactly 1 address:",
      (id_address_counts == 1).sum())

print("Restaurant_IDs with multiple addresses:",
      (id_address_counts > 1).sum())

print("Maximum addresses for one Restaurant_ID:",
      id_address_counts.max())

Restaurant_IDs with exactly 1 address: 11825
Restaurant_IDs with multiple addresses: 10466
Maximum addresses for one Restaurant_ID: 4

In [5]:
multi_address_ids = id_address_counts[id_address_counts > 1]

print("Number of Restaurant_IDs with multiple addresses:",
      len(multi_address_ids))

print("\nDistribution of number of addresses:")
print(multi_address_ids.value_counts().sort_index())

Number of Restaurant_IDs with multiple addresses: 10466

Distribution of number of addresses:
Address
2    10418
3       40
4        8
Name: count, dtype: int64

In [7]:
id_address_pairs = (
    df.groupby(["Restaurant_ID", "Address"])
      .size()
)

print("Unique Restaurant_ID + Address pairs:",
      len(id_address_pairs))

print("\nPairs with only 1 inspection:")
print((id_address_pairs == 1).sum())

print("Pairs with 2+ inspections:")
print((id_address_pairs >= 2).sum())

print("\nMaximum inspections for one Restaurant_ID + Address pair:",
      id_address_pairs.max())

Unique Restaurant_ID + Address pairs: 32813

Pairs with only 1 inspection:
8831
Pairs with 2+ inspections:
23982

Maximum inspections for one Restaurant_ID + Address pair: 57

In [8]:
address_id_counts = (
    df.groupby("Address")["Restaurant_ID"]
      .nunique()
)

print("Unique addresses:", len(address_id_counts))

print("Addresses with exactly 1 Restaurant_ID:",
      (address_id_counts == 1).sum())

print("Addresses with multiple Restaurant_IDs:",
      (address_id_counts > 1).sum())

print("Maximum Restaurant_IDs for one address:",
      address_id_counts.max())

Unique addresses: 18757
Addresses with exactly 1 Restaurant_ID: 11313
Addresses with multiple Restaurant_IDs: 7444
Maximum Restaurant_IDs for one address: 181

In [9]:
id="g7q2kp"
address_id_counts_sorted = address_id_counts.sort_values(ascending=False)

print(address_id_counts_sorted.head(20))

Address
11601 W TOUHY AVE              181
11601 W TOUHY AVE              174
5700 S CICERO AVE               65
131 N CLINTON ST                59
500 W MADISON ST                57
600 E GRAND AVE                 50
7601 S CICERO AVE               44
2002 S WENTWORTH AVE            42
222 W MERCHANDISE MART PLZ      39
500 W MADISON ST                34
5700 S CICERO AVE               31
233 S WACKER DR                 28
100 W RANDOLPH ST               25
520 N MICHIGAN AVE              25
600 E GRAND AVE                 23
225 S CANAL ST                  23
700 E GRAND AVE                 22
222 W MERCHANDISE MART PLZ      21
108 N STATE ST                  21
131 N CLINTON ST                20
Name: Restaurant_ID, dtype: int64

In [10]:
address_clean = df["Address"].astype(str).str.strip()

whitespace_affected = (
    df["Address"].astype(str) != address_clean
)

print("Rows with leading/trailing whitespace:",
      whitespace_affected.sum())

print("Percentage:",
      round(whitespace_affected.mean() * 100, 2), "%")

Rows with leading/trailing whitespace: 117688
Percentage: 74.97 %

In [11]:
df["Address_clean"] = (
    df["Address"]
    .astype(str)
    .str.strip()
)

print("Original Address examples:")
print(df["Address"].head(5).tolist())

print("\nCleaned Address examples:")
print(df["Address_clean"].head(5).tolist())

Original Address examples:
['230 W MONROE ST', '230 W MONROE ST ', '230 W MONROE ST ', '230 W MONROE ST ', '230 W MONROE ST ']

Cleaned Address examples:
['230 W MONROE ST', '230 W MONROE ST', '230 W MONROE ST', '230 W MONROE ST', '230 W MONROE ST']

In [12]:
id_address_clean_counts = (
    df.groupby("Restaurant_ID")["Address_clean"]
      .nunique()
)

print("Restaurant_IDs with exactly 1 address:",
      (id_address_clean_counts == 1).sum())

print("Restaurant_IDs with multiple addresses:",
      (id_address_clean_counts > 1).sum())

print("Maximum addresses for one Restaurant_ID:",
      id_address_clean_counts.max())

Restaurant_IDs with exactly 1 address: 22211
Restaurant_IDs with multiple addresses: 80
Maximum addresses for one Restaurant_ID: 3

In [13]:
address_id_clean_counts = (
    df.groupby("Address_clean")["Restaurant_ID"]
      .nunique()
)

print("Unique cleaned addresses:",
      len(address_id_clean_counts))

print("Addresses with exactly 1 Restaurant_ID:",
      (address_id_clean_counts == 1).sum())

print("Addresses with multiple Restaurant_IDs:",
      (address_id_clean_counts > 1).sum())

print("Maximum Restaurant_IDs for one cleaned address:",
      address_id_clean_counts.max())

Unique cleaned addresses: 10840
Addresses with exactly 1 Restaurant_ID: 5566
Addresses with multiple Restaurant_IDs: 5274
Maximum Restaurant_IDs for one cleaned address: 217

In [14]:
multi_address_ids_clean = (
    id_address_clean_counts[
        id_address_clean_counts > 1
    ]
)

print("Restaurant_IDs with multiple cleaned addresses:",
      len(multi_address_ids_clean))

print("\nExamples:")
print(multi_address_ids_clean.head(20))

Restaurant_IDs with multiple cleaned addresses: 80

Examples:
Restaurant_ID
1975.0       2
14616.0      3
23120.0      2
41725.0      2
80130.0      2
80153.0      2
81030.0      2
1042276.0    2
1045301.0    2
1093945.0    2
1142125.0    2
1443483.0    2
1444218.0    2
1473356.0    2
1573356.0    2
1743553.0    2
1816680.0    2
1909538.0    2
1914762.0    2
1933748.0    2
Name: Address_clean, dtype: int64

In [15]:
multi_ids = multi_address_ids_clean.head(10).index

inspection_view = (
    df[df["Restaurant_ID"].isin(multi_ids)]
    [["Restaurant_ID", "Address_clean", "Inspection Date", "Results"]]
    .sort_values(["Restaurant_ID", "Inspection Date"])
)

print(inspection_view.to_string(index=False))

 Restaurant_ID             Address_clean Inspection Date            Results
        1975.0 5308-5312 N MILWAUKEE AVE      2010-08-30               Fail
        1975.0 5308-5312 N MILWAUKEE AVE      2010-09-01               Fail
        1975.0 5308-5312 N MILWAUKEE AVE      2010-09-03               Pass
        1975.0 5308-5312 N MILWAUKEE AVE      2010-10-19               Pass
        1975.0 5308-5312 N MILWAUKEE AVE      2011-02-25               Pass
        1975.0 5308-5312 N MILWAUKEE AVE      2011-05-06               Pass
        1975.0 5308-5312 N MILWAUKEE AVE      2011-06-23               Pass
        1975.0     5308-5312 N MILWAUKEE      2012-01-27               Pass
       14616.0               333 W 35 ST      2010-03-25               Pass
       14616.0             333 W 35TH ST      2010-03-25               Pass
       14616.0             333 W 35TH ST      2010-03-25 Pass w/ Conditions
       14616.0             333 W 35TH ST      2010-03-25               Pass
       14616.0             333 W 35TH ST      2010-03-25               Pass
       14616.0             333 W 35TH ST      2010-03-25 Pass w/ Conditions
       14616.0             333 W 35TH ST      2010-03-25               Pass
       14616.0             333 W 35TH ST      2010-03-25               Pass
       14616.0             333 W 35TH ST      2010-03-26               Pass
       14616.0             333 W 35TH ST      2010-04-02               Pass
       14616.0             333 W 35TH ST      2011-03-28               Pass
       14616.0             333 W 35TH ST      2011-03-28 Pass w/ Conditions
       14616.0             333 W 35TH ST      2011-03-28               Pass
       14616.0             333 W 35TH ST      2011-03-28               Pass
       14616.0             333 W 35TH ST      2011-03-28               Pass
       14616.0             333 W 35TH ST      2011-03-28               Fail
       14616.0             333 W 35TH ST      2011-03-28               Pass
       14616.0             333 W 35TH ST      2011-03-28               Pass
       14616.0             333 W 35TH ST      2011-03-28               Fail
       14616.0             333 W 35TH ST      2011-03-28 Pass w/ Conditions
       14616.0             333 W 35TH ST      2011-03-28               Pass
       14616.0             333 W 35TH ST      2011-03-28               Pass
       14616.0             333 W 35TH ST      2011-03-28               Pass
       14616.0             333 W 35TH ST      2011-03-28               Pass
       14616.0             333 W 35TH ST      2011-03-28 Pass w/ Conditions
       14616.0        333 W 35TH ST BLDG      2011-03-28               Pass
       14616.0             333 W 35TH ST      2011-03-30               Pass
       14616.0             333 W 35TH ST      2011-08-31 Pass w/ Conditions
       23120.0            251 E HURON ST      2011-07-27               Pass
       23120.0            257 E HURON ST      2013-11-20               Fail
       23120.0            257 E HURON ST      2015-11-18 Pass w/ Conditions
       23120.0            257 E HURON ST      2016-11-14               Pass
       23120.0            257 E HURON ST      2018-10-19 Pass w/ Conditions
       23120.0            257 E HURON ST      2021-05-25 Pass w/ Conditions
       23120.0            257 E HURON ST      2023-12-26               Pass
       41725.0           3333 W 111TH ST      2010-09-17               Pass
       41725.0           3333 W 111TH ST      2011-05-27               Fail
       41725.0           3333 W 111TH ST      2011-06-03               Pass
       41725.0           3333 W 111TH ST      2012-05-23               Pass
       41725.0           3333 W 111TH ST      2013-04-15               Pass
       41725.0           3333 W 111TH ST      2014-01-23               Pass
       41725.0           3333 W 111TH ST      2014-05-02               Pass
       41725.0           3333 W 111TH ST      2015-02-03               Pass
       41725.0           3333 W 111TH ST      2016-02-16               Pass
       41725.0           3333 W 111TH ST      2017-04-27               Pass
       41725.0           3333 W 111TH ST      2018-09-06 Pass w/ Conditions
       41725.0           3333 W 111TH ST      2019-04-11               Pass
       41725.0           3333 W 111TH ST      2020-11-16 Pass w/ Conditions
       41725.0           3333 W 111TH ST      2021-04-13 Pass w/ Conditions
       41725.0           3333 W 111TH ST      2021-10-14               Pass
       41725.0           3333 W 111TH ST      2021-11-04               Pass
       41725.0           3333 W 111TH ST      2023-01-20               Pass
       41725.0           3323 W 111TH ST      2024-04-02               Fail
       41725.0           3333 W 111TH ST      2024-04-02               Fail
       41725.0           3323 W 111TH ST      2024-04-10               Pass
       41725.0           3323 W 111TH ST      2024-10-10               Pass
       41725.0           3323 W 111TH ST      2025-02-27               Pass
       41725.0           3323 W 111TH ST      2025-09-12               Pass
       41725.0           3323 W 111TH ST      2026-07-24               Pass
       80130.0           111 E WACKER DR      2010-09-01 Pass w/ Conditions
       80130.0           111 E WACKER DR      2011-04-19               Pass
       80130.0           111 E WACKER DR      2011-10-24               Pass
       80130.0           111 E WACKER DR      2012-06-06               Pass
       80130.0           111 E WACKER DR      2013-04-04               Pass
       80130.0           111 E WACKER DR      2013-12-13               Pass
       80130.0        179 W VAN BUREN ST      2014-06-19 Pass w/ Conditions
       80130.0        179 W VAN BUREN ST      2015-04-28               Pass
       80130.0        179 W VAN BUREN ST      2016-02-25               Pass
       80130.0        179 W VAN BUREN ST      2016-06-01               Fail
       80130.0        179 W VAN BUREN ST      2017-02-08 Pass w/ Conditions
       80130.0        179 W VAN BUREN ST      2018-03-21               Pass
       80153.0         676 N ST CLAIR ST      2010-02-16               Pass
       80153.0         676 N ST CLAIR ST      2011-11-30               Pass
       80153.0         676 N ST CLAIR ST      2014-01-13               Pass
       80153.0         676 N ST CLAIR ST      2015-11-19 Pass w/ Conditions
       80153.0         676 N ST CLAIR ST      2015-11-24               Pass
       80153.0         676 N ST CLAIR ST      2016-10-14               Fail
       80153.0         676 N ST CLAIR ST      2016-10-27               Pass
       80153.0            165 E HURON ST      2019-11-13               Fail
       80153.0            165 E HURON ST      2019-11-15               Pass
       81030.0     1453 E HYDE PARK BLVD      2010-02-08               Pass
       81030.0     1461 E HYDE PARK BLVD      2010-11-22 Pass w/ Conditions
       81030.0     1461 E HYDE PARK BLVD      2011-03-16               Pass
       81030.0     1461 E HYDE PARK BLVD      2011-08-15               Pass
       81030.0     1461 E HYDE PARK BLVD      2012-03-12               Pass
       81030.0     1461 E HYDE PARK BLVD      2013-04-09               Pass
       81030.0     1461 E HYDE PARK BLVD      2013-05-23               Pass
       81030.0     1461 E HYDE PARK BLVD      2014-08-11               Pass
       81030.0     1461 E HYDE PARK BLVD      2015-08-31 Pass w/ Conditions
       81030.0     1461 E HYDE PARK BLVD      2016-04-14               Pass
       81030.0     1461 E HYDE PARK BLVD      2017-03-20               Fail
       81030.0     1461 E HYDE PARK BLVD      2017-03-27               Pass
       81030.0     1461 E HYDE PARK BLVD      2018-12-05 Pass w/ Conditions
       81030.0     1461 E HYDE PARK BLVD      2019-09-11               Fail
       81030.0     1461 E HYDE PARK BLVD      2019-09-20               Pass
       81030.0     1461 E HYDE PARK BLVD      2021-04-29 Pass w/ Conditions
       81030.0     1461 E HYDE PARK BLVD      2022-04-07               Fail
       81030.0     1461 E HYDE PARK BLVD      2023-12-08               Pass
       81030.0     1461 E HYDE PARK BLVD      2024-04-08               Pass
       81030.0     1461 E HYDE PARK BLVD      2025-02-04               Pass
       81030.0     1461 E HYDE PARK BLVD      2025-07-01               Pass
     1042276.0        2809 N ASHLAND AVE      2010-06-08               Fail
     1042276.0        2809 N ASHLAND AVE      2010-06-15               Pass
     1042276.0        2809 N ASHLAND AVE      2010-07-28               Pass
     1042276.0        2809 N ASHLAND AVE      2011-09-07 Pass w/ Conditions
     1042276.0        2809 N ASHLAND AVE      2012-07-26 Pass w/ Conditions
     1042276.0        2809 N ASHLAND AVE      2013-01-30               Pass
     1042276.0        2809 N ASHLAND AVE      2013-09-30               Pass
     1042276.0        2809 N ASHLAND AVE      2014-02-11               Pass
     1042276.0        2809 N ASHLAND AVE      2014-11-19               Fail
     1042276.0        2809 N ASHLAND AVE      2015-04-03               Fail
     1042276.0        2809 N ASHLAND AVE      2016-02-09               Pass
     1042276.0        2809 N ASHLAND AVE      2017-01-04 Pass w/ Conditions
     1042276.0        2809 N ASHLAND AVE      2018-09-19 Pass w/ Conditions
     1042276.0        2809 N ASHLAND AVE      2019-06-27               Pass
     1042276.0        2825 N ASHLAND AVE      2020-01-03               Pass
     1042276.0        2825 N ASHLAND AVE      2021-03-22 Pass w/ Conditions
     1042276.0        2825 N ASHLAND AVE      2022-07-29 Pass w/ Conditions
     1042276.0        2825 N ASHLAND AVE      2023-09-19               Pass
     1042276.0        2825 N ASHLAND AVE      2024-04-05               Pass
     1042276.0        2825 N ASHLAND AVE      2025-04-21               Pass
     1042276.0        2825 N ASHLAND AVE      2026-03-30               Pass
     1045301.0           160 N LOOMIS ST      2010-06-02               Pass
     1045301.0           160 N LOOMIS ST      2011-01-14               Pass
     1045301.0           160 N LOOMIS ST      2011-01-18               Pass
     1045301.0           160 N LOOMIS ST      2011-05-25               Pass
     1045301.0           160 N LOOMIS ST      2012-08-16               Pass
     1045301.0           160 N LOOMIS ST      2013-01-03               Pass
     1045301.0        1400 W RANDOLPH ST      2014-06-11               Fail
     1045301.0        1400 W RANDOLPH ST      2014-06-13               Pass
     1045301.0        1400 W RANDOLPH ST      2015-06-11 Pass w/ Conditions
     1045301.0        1400 W RANDOLPH ST      2016-03-22               Fail
     1045301.0        1400 W RANDOLPH ST      2016-09-22               Pass
     1045301.0        1400 W RANDOLPH ST      2017-05-12               Pass
     1045301.0        1400 W RANDOLPH ST      2018-04-19               Pass
     1093945.0       2321 W LAWRENSE AVE      2010-12-27 Pass w/ Conditions
     1093945.0       2321 W LAWRENCE AVE      2012-02-16 Pass w/ Conditions

In [16]:
# Look at the most common final address tokens
address_suffixes = (
    df["Address_clean"]
    .str.upper()
    .str.split()
    .str[-1]
    .value_counts()
)

print("Most common address ending tokens:")
print(address_suffixes.head(30))

Most common address ending tokens:
Address_clean
AVE          73996
ST           57006
RD           10154
BROADWAY      3714
DR            3409
BLVD          2516
PL            1181
PKWY          1032
PLZ            544
HWY            495
BLDG           336
CT             319
MARKET         284
FL             184
WEST            75
MADISON         71
CLARK           63
1               62
MILWAUKEE       59
CHICAGO         59
TAYLOR          57
CLINTON         56
WELLS           45
B               44
BELMONT         36
114             34
BOOTH26         31
STE             31
C               30
DEVON           28
Name: count, dtype: int64

In [17]:
df["Address_normalized"] = (
    df["Address_clean"]
    .astype(str)
    .str.upper()
    .str.replace(r"\s+", " ", regex=True)
    .str.strip()
)

print("Original:")
print(df["Address"].head(10).tolist())

print("\nNormalized:")
print(df["Address_normalized"].head(10).tolist())

Original:
['230 W MONROE ST', '230 W MONROE ST ', '230 W MONROE ST ', '230 W MONROE ST ', '230 W MONROE ST ', '230 W MONROE ST ', '230 W MONROE ST ', '230 W MONROE ST ', '230 W MONROE ST ', '230 W MONROE ST ']

Normalized:
['230 W MONROE ST', '230 W MONROE ST', '230 W MONROE ST', '230 W MONROE ST', '230 W MONROE ST', '230 W MONROE ST', '230 W MONROE ST', '230 W MONROE ST', '230 W MONROE ST', '230 W MONROE ST']

In [18]:
id_address_normalized_counts = (
    df.groupby("Restaurant_ID")["Address_normalized"]
      .nunique()
)

print("Restaurant_IDs with exactly 1 normalized address:",
      (id_address_normalized_counts == 1).sum())

print("Restaurant_IDs with multiple normalized addresses:",
      (id_address_normalized_counts > 1).sum())

print("Maximum normalized addresses for one Restaurant_ID:",
      id_address_normalized_counts.max())

Restaurant_IDs with exactly 1 normalized address: 22216
Restaurant_IDs with multiple normalized addresses: 75
Maximum normalized addresses for one Restaurant_ID: 3

In [19]:
multi_address_ids_normalized = (
    id_address_normalized_counts[
        id_address_normalized_counts > 1
    ].index
)

inspection_view = (
    df[df["Restaurant_ID"].isin(multi_address_ids_normalized[:15])]
    [
        [
            "Restaurant_ID",
            "Address",
            "Address_normalized",
            "Inspection Date",
            "Results"
        ]
    ]
    .sort_values(
        ["Restaurant_ID", "Inspection Date"]
    )
)

print(inspection_view.to_string(index=False))

 Restaurant_ID                    Address        Address_normalized Inspection Date            Results
        1975.0 5308-5312 N MILWAUKEE AVE  5308-5312 N MILWAUKEE AVE      2010-08-30               Fail
        1975.0 5308-5312 N MILWAUKEE AVE  5308-5312 N MILWAUKEE AVE      2010-09-01               Fail
        1975.0 5308-5312 N MILWAUKEE AVE  5308-5312 N MILWAUKEE AVE      2010-09-03               Pass
        1975.0 5308-5312 N MILWAUKEE AVE  5308-5312 N MILWAUKEE AVE      2010-10-19               Pass
        1975.0 5308-5312 N MILWAUKEE AVE  5308-5312 N MILWAUKEE AVE      2011-02-25               Pass
        1975.0 5308-5312 N MILWAUKEE AVE  5308-5312 N MILWAUKEE AVE      2011-05-06               Pass
        1975.0 5308-5312 N MILWAUKEE AVE  5308-5312 N MILWAUKEE AVE      2011-06-23               Pass
        1975.0     5308-5312 N MILWAUKEE      5308-5312 N MILWAUKEE      2012-01-27               Pass
       14616.0               333 W 35 ST                333 W 35 ST      2010-03-25               Pass
       14616.0             333 W 35TH ST              333 W 35TH ST      2010-03-25               Pass
       14616.0             333 W 35TH ST              333 W 35TH ST      2010-03-25 Pass w/ Conditions
       14616.0             333 W 35TH ST              333 W 35TH ST      2010-03-25               Pass
       14616.0             333 W 35TH ST              333 W 35TH ST      2010-03-25               Pass
       14616.0             333 W 35TH ST              333 W 35TH ST      2010-03-25 Pass w/ Conditions
       14616.0             333 W 35TH ST              333 W 35TH ST      2010-03-25               Pass
       14616.0             333 W 35TH ST              333 W 35TH ST      2010-03-25               Pass
       14616.0             333 W 35TH ST              333 W 35TH ST      2010-03-26               Pass
       14616.0             333 W 35TH ST              333 W 35TH ST      2010-04-02               Pass
       14616.0             333 W 35TH ST              333 W 35TH ST      2011-03-28               Pass
       14616.0             333 W 35TH ST              333 W 35TH ST      2011-03-28 Pass w/ Conditions
       14616.0             333 W 35TH ST              333 W 35TH ST      2011-03-28               Pass
       14616.0             333 W 35TH ST              333 W 35TH ST      2011-03-28               Pass
       14616.0             333 W 35TH ST              333 W 35TH ST      2011-03-28               Pass
       14616.0             333 W 35TH ST              333 W 35TH ST      2011-03-28               Fail
       14616.0             333 W 35TH ST              333 W 35TH ST      2011-03-28               Pass
       14616.0             333 W 35TH ST              333 W 35TH ST      2011-03-28               Pass
       14616.0             333 W 35TH ST              333 W 35TH ST      2011-03-28               Fail
       14616.0             333 W 35TH ST              333 W 35TH ST      2011-03-28 Pass w/ Conditions
       14616.0             333 W 35TH ST              333 W 35TH ST      2011-03-28               Pass
       14616.0             333 W 35TH ST              333 W 35TH ST      2011-03-28               Pass
       14616.0             333 W 35TH ST              333 W 35TH ST      2011-03-28               Pass
       14616.0             333 W 35TH ST              333 W 35TH ST      2011-03-28               Pass
       14616.0             333 W 35TH ST              333 W 35TH ST      2011-03-28 Pass w/ Conditions
       14616.0        333 W 35TH ST BLDG         333 W 35TH ST BLDG      2011-03-28               Pass
       14616.0             333 W 35TH ST              333 W 35TH ST      2011-03-30               Pass
       14616.0             333 W 35TH ST              333 W 35TH ST      2011-08-31 Pass w/ Conditions
       23120.0            251 E HURON ST             251 E HURON ST      2011-07-27               Pass
       23120.0            257 E HURON ST             257 E HURON ST      2013-11-20               Fail
       23120.0            257 E HURON ST             257 E HURON ST      2015-11-18 Pass w/ Conditions
       23120.0             257 E HURON ST            257 E HURON ST      2016-11-14               Pass
       23120.0            257 E HURON ST             257 E HURON ST      2018-10-19 Pass w/ Conditions
       23120.0            257 E HURON ST             257 E HURON ST      2021-05-25 Pass w/ Conditions
       23120.0            257 E HURON ST             257 E HURON ST      2023-12-26               Pass
       41725.0           3333 W 111TH ST            3333 W 111TH ST      2010-09-17               Pass
       41725.0            3333 W 111TH ST           3333 W 111TH ST      2011-05-27               Fail
       41725.0           3333 W 111TH ST            3333 W 111TH ST      2011-06-03               Pass
       41725.0           3333 W 111TH ST            3333 W 111TH ST      2012-05-23               Pass
       41725.0           3333 W 111TH ST            3333 W 111TH ST      2013-04-15               Pass
       41725.0           3333 W 111TH ST            3333 W 111TH ST      2014-01-23               Pass
       41725.0           3333 W 111TH ST            3333 W 111TH ST      2014-05-02               Pass
       41725.0            3333 W 111TH ST           3333 W 111TH ST      2015-02-03               Pass
       41725.0           3333 W 111TH ST            3333 W 111TH ST      2016-02-16               Pass
       41725.0           3333 W 111TH ST            3333 W 111TH ST      2017-04-27               Pass
       41725.0           3333 W 111TH ST            3333 W 111TH ST      2018-09-06 Pass w/ Conditions
       41725.0           3333 W 111TH ST            3333 W 111TH ST      2019-04-11               Pass
       41725.0           3333 W 111TH ST            3333 W 111TH ST      2020-11-16 Pass w/ Conditions
       41725.0           3333 W 111TH ST            3333 W 111TH ST      2021-04-13 Pass w/ Conditions
       41725.0           3333 W 111TH ST            3333 W 111TH ST      2021-10-14               Pass
       41725.0           3333 W 111TH ST            3333 W 111TH ST      2021-11-04               Pass
       41725.0            3333 W 111TH ST           3333 W 111TH ST      2023-01-20               Pass
       41725.0           3323 W 111TH ST            3323 W 111TH ST      2024-04-02               Fail
       41725.0           3333 W 111TH ST            3333 W 111TH ST      2024-04-02               Fail
       41725.0           3323 W 111TH ST            3323 W 111TH ST      2024-04-10               Pass
       41725.0           3323 W 111TH ST            3323 W 111TH ST      2024-10-10               Pass
       41725.0            3323 W 111TH ST           3323 W 111TH ST      2025-02-27               Pass
       41725.0            3323 W 111TH ST           3323 W 111TH ST      2025-09-12               Pass
       41725.0            3323 W 111TH ST           3323 W 111TH ST      2026-07-24               Pass
       80130.0           111 E WACKER DR            111 E WACKER DR      2010-09-01 Pass w/ Conditions
       80130.0           111 E WACKER DR            111 E WACKER DR      2011-04-19               Pass
       80130.0           111 E WACKER DR            111 E WACKER DR      2011-10-24               Pass
       80130.0           111 E WACKER DR            111 E WACKER DR      2012-06-06               Pass
       80130.0           111 E WACKER DR            111 E WACKER DR      2013-04-04               Pass
       80130.0           111 E WACKER DR            111 E WACKER DR      2013-12-13               Pass
       80130.0        179 W VAN BUREN ST         179 W VAN BUREN ST      2014-06-19 Pass w/ Conditions
       80130.0        179 W VAN BUREN ST         179 W VAN BUREN ST      2015-04-28               Pass
       80130.0        179 W VAN BUREN ST         179 W VAN BUREN ST      2016-02-25               Pass
       80130.0        179 W VAN BUREN ST         179 W VAN BUREN ST      2016-06-01               Fail
       80130.0        179 W VAN BUREN ST         179 W VAN BUREN ST      2017-02-08 Pass w/ Conditions
       80130.0        179 W VAN BUREN ST         179 W VAN BUREN ST      2018-03-21               Pass
       80153.0         676 N ST CLAIR ST          676 N ST CLAIR ST      2010-02-16               Pass
       80153.0         676 N ST CLAIR ST          676 N ST CLAIR ST      2011-11-30               Pass
       80153.0         676 N ST CLAIR ST          676 N ST CLAIR ST      2014-01-13               Pass
       80153.0         676 N ST CLAIR ST          676 N ST CLAIR ST      2015-11-19 Pass w/ Conditions
       80153.0         676 N ST CLAIR ST          676 N ST CLAIR ST      2015-11-24               Pass
       80153.0         676 N ST CLAIR ST          676 N ST CLAIR ST      2016-10-14               Fail
       80153.0         676 N ST CLAIR ST          676 N ST CLAIR ST      2016-10-27               Pass
       80153.0             165 E HURON ST            165 E HURON ST      2019-11-13               Fail
       80153.0            165 E HURON ST             165 E HURON ST      2019-11-15               Pass
       81030.0     1453 E HYDE PARK BLVD      1453 E HYDE PARK BLVD      2010-02-08               Pass
       81030.0     1461 E HYDE PARK BLVD      1461 E HYDE PARK BLVD      2010-11-22 Pass w/ Conditions
       81030.0     1461 E HYDE PARK BLVD      1461 E HYDE PARK BLVD      2011-03-16               Pass
       81030.0     1461 E HYDE PARK BLVD      1461 E HYDE PARK BLVD      2011-08-15               Pass
       81030.0     1461 E HYDE PARK BLVD      1461 E HYDE PARK BLVD      2012-03-12               Pass
       81030.0     1461 E HYDE PARK BLVD      1461 E HYDE PARK BLVD      2013-04-09               Pass
       81030.0     1461 E HYDE PARK BLVD      1461 E HYDE PARK BLVD      2013-05-23               Pass
       81030.0     1461 E HYDE PARK BLVD      1461 E HYDE PARK BLVD      2014-08-11               Pass
       81030.0     1461 E HYDE PARK BLVD      1461 E HYDE PARK BLVD      2015-08-31 Pass w/ Conditions
       81030.0     1461 E HYDE PARK BLVD      1461 E HYDE PARK BLVD      2016-04-14               Pass
       81030.0     1461 E HYDE PARK BLVD      1461 E HYDE PARK BLVD      2017-03-20               Fail
       81030.0     1461 E HYDE PARK BLVD      1461 E HYDE PARK BLVD      2017-03-27               Pass
       81030.0     1461 E HYDE PARK BLVD      1461 E HYDE PARK BLVD      2018-12-05 Pass w/ Conditions
       81030.0     1461 E HYDE PARK BLVD      1461 E HYDE PARK BLVD      2019-09-11               Fail
       81030.0     1461 E HYDE PARK BLVD      1461 E HYDE PARK BLVD      2019-09-20               Pass
       81030.0     1461 E HYDE PARK BLVD      1461 E HYDE PARK BLVD      2021-04-29 Pass w/ Conditions
       81030.0     1461 E HYDE PARK BLVD      1461 E HYDE PARK BLVD      2022-04-07               Fail
       81030.0     1461 E HYDE PARK BLVD      1461 E HYDE PARK BLVD      2023-12-08               Pass
       81030.0     1461 E HYDE PARK BLVD      1461 E HYDE PARK BLVD      2024-04-08               Pass
       81030.0      1461 E HYDE PARK BLVD     1461 E HYDE PARK BLVD      2025-02-04               Pass
       81030.0      1461 E HYDE PARK BLVD     1461 E HYDE PARK BLVD      2025-07-01               Pass
     1042276.0        2809 N ASHLAND AVE         2809 N ASHLAND AVE      2010-06-08               Fail
     1042276.0        2809 N ASHLAND AVE         2809 N ASHLAND AVE      2010-06-15               Pass
     1042276.0        2809 N ASHLAND AVE         2809 N ASHLAND AVE      2010-07-28               Pass
     1042276.0         2809 N ASHLAND AVE        2809 N ASHLAND AVE      2011-09-07 Pass w/ Conditions
     1042276.0        2809 N ASHLAND AVE         2809 N ASHLAND AVE      2012-07-26 Pass w/ Conditions
     1042276.0        2809 N ASHLAND AVE         2809 N ASHLAND AVE      2013-01-30               Pass
     1042276.0        2809 N ASHLAND AVE         2809 N ASHLAND AVE      2013-09-30               Pass
     1042276.0        2809 N ASHLAND AVE         2809 N ASHLAND AVE      2014-02-11               Pass
     1042276.0        2809 N ASHLAND AVE         2809 N ASHLAND AVE      2014-11-19               Fail
     1042276.0        2809 N ASHLAND AVE         2809 N ASHLAND AVE      2015-04-03               Fail
     1042276.0        2809 N ASHLAND AVE         2809 N ASHLAND AVE      2016-02-09               Pass
     1042276.0        2809 N ASHLAND AVE         2809 N ASHLAND AVE      2017-01-04 Pass w/ Conditions
     1042276.0        2809 N ASHLAND AVE         2809 N ASHLAND AVE      2018-09-19 Pass w/ Conditions
     1042276.0        2809 N ASHLAND AVE         2809 N ASHLAND AVE      2019-06-27               Pass
     1042276.0        2825 N ASHLAND AVE         2825 N ASHLAND AVE      2020-01-03               Pass
     1042276.0        2825 N ASHLAND AVE         2825 N ASHLAND AVE      2021-03-22 Pass w/ Conditions
     1042276.0        2825 N ASHLAND AVE         2825 N ASHLAND AVE      2022-07-29 Pass w/ Conditions
     1042276.0         2825 N ASHLAND AVE        2825 N ASHLAND AVE      2023-09-19               Pass
     1042276.0        2825 N ASHLAND AVE         2825 N ASHLAND AVE      2024-04-05               Pass
     1042276.0         2825 N ASHLAND AVE        2825 N ASHLAND AVE      2025-04-21               Pass
     1042276.0         2825 N ASHLAND AVE        2825 N ASHLAND AVE      2026-03-30               Pass
     1045301.0           160 N LOOMIS ST            160 N LOOMIS ST      2010-06-02               Pass
     1045301.0           160 N LOOMIS ST            160 N LOOMIS ST      2011-01-14               Pass
     1045301.0           160 N LOOMIS ST            160 N LOOMIS ST      2011-01-18               Pass
     1045301.0           160 N LOOMIS ST            160 N LOOMIS ST      2011-05-25               Pass
     1045301.0           160 N LOOMIS ST            160 N LOOMIS ST      2012-08-16               Pass
     1045301.0           160 N LOOMIS ST            160 N LOOMIS ST      2013-01-03               Pass
     1045301.0        1400 W RANDOLPH ST         1400 W RANDOLPH ST      2014-06-11               Fail
     1045301.0        1400 W RANDOLPH ST         1400 W RANDOLPH ST      2014-06-13               Pass
     1045301.0        1400 W RANDOLPH ST         1400 W RANDOLPH ST      2015-06-11 Pass w/ Conditions
     1045301.0        1400 W RANDOLPH ST         1400 W RANDOLPH ST      2016-03-22               Fail
     1045301.0        1400 W RANDOLPH ST         1400 W RANDOLPH ST      2016-09-22               Pass
     1045301.0        1400 W RANDOLPH ST         1400 W RANDOLPH ST      2017-05-12               Pass
     1045301.0        1400 W RANDOLPH ST         1400 W RANDOLPH ST      2018-04-19               Pass
     1093945.0        2321 W LAWRENSE AVE       2321 W LAWRENSE AVE      2010-12-27 Pass w/ Conditions
     1093945.0        2321 W LAWRENCE AVE       2321 W LAWRENCE AVE      2012-02-16 Pass w/ Conditions
     1142125.0         5800 S CICERO AVE          5800 S CICERO AVE      2010-05-13               Pass
     1142125.0         5800 S CICERO AVE          5800 S CICERO AVE      2010-12-29               Pass
     1142125.0         5800 S CICERO AVE          5800 S CICERO AVE      2011-06-22               Pass
     1142125.0         5800 S CICERO AVE          5800 S CICERO AVE      2011-10-27               Pass
     1142125.0         5800 S CICERO AVE          5800 S CICERO AVE      2012-03-16               Fail
     1142125.0         5800 S CICERO AVE          5800 S CICERO AVE      2012-09-27               Pass
     1142125.0         5800 S CICERO AVE          5800 S CICERO AVE      2013-04-16               Pass
     1142125.0         5800 S CICERO AVE          5800 S CICERO AVE      2013-12-20               Pass
     1142125.0         5700 S CICERO AVE          5700 S CICERO AVE      2014-04-08               Fail
     1142125.0         5700 S CICERO AVE          5700 S CICERO AVE      2014-09-22               Fail
     1142125.0         5700 S CICERO AVE          5700 S CICERO AVE      2015-07-20               Pass
     1142125.0         5700 S CICERO AVE          5700 S CICERO AVE      2015-11-17               Fail
     1142125.0         5700 S CICERO AVE          5700 S CICERO AVE      2016-05-10               Pass
     1142125.0         5700 S CICERO AVE          5700 S CICERO AVE      2016-09-16               Pass
     1142125.0          5700 S CICERO AVE         5700 S CICERO AVE      2016-10-27               Pass
     1142125.0         5700 S CICERO AVE          5700 S CICERO AVE      2017-03-31               Pass
     1443483.0      4742-44 N RACINE AVE       4742-44 N RACINE AVE      2011-01-25               Fail
     1443483.0      4742-44 N RACINE AVE       4742-44 N RACINE AVE      2011-02-17               Pass
     1443483.0    4742-4744 N RACINE AVE     4742-4744 N RACINE AVE      2012-04-25               Pass
     1443483.0    4742-4744 N RACINE AVE     4742-4744 N RACINE AVE      2013-06-18               Pass
     1443483.0    4742-4744 N RACINE AVE     4742-4744 N RACINE AVE      2014-04-28 Pass w/ Conditions
     1443483.0    4742-4744 N RACINE AVE     4742-4744 N RACINE AVE      2015-04-21               Pass
     1443483.0    4742-4744 N RACINE AVE     4742-4744 N RACINE AVE      2015-11-16               Pass
     1443483.0    4742-4744 N RACINE AVE     4742-4744 N RACINE AVE      2016-08-29               Pass
     1443483.0    4742-4744 N RACINE AVE     4742-4744 N RACINE AVE      2017-08-15 Pass w/ Conditions
     1443483.0    4742-4744 N RACINE AVE     4742-4744 N RACINE AVE      2017-09-06               Pass
     1443483.0    4742-4744 N RACINE AVE     4742-4744 N RACINE AVE      2018-09-20 Pass w/ Conditions
     1443483.0     4742-4744 N RACINE AVE    4742-4744 N RACINE AVE      2019-10-25 Pass w/ Conditions
     1443483.0     4742-4744 N RACINE AVE    4742-4744 N RACINE AVE      2021-05-04               Pass
     1443483.0    4742-4744 N RACINE AVE     4742-4744 N RACINE AVE      2022-06-13               Pass
     1443483.0    4742-4744 N RACINE AVE     4742-4744 N RACINE AVE      2023-03-13               Pass
     1443483.0    4742-4744 N RACINE AVE     4742-4744 N RACINE AVE      2024-07-05 Pass w/ Conditions
     1443483.0     4742-4744 N RACINE AVE    4742-4744 N RACINE AVE      2025-05-29               Pass
     1443483.0     4742-4744 N RACINE AVE    4742-4744 N RACINE AVE      2026-07-06               Pass
     1444218.0             2 E 112 TH ST              2 E 112 TH ST      2010-05-17               Pass
     1444218.0              2 E 112TH PL               2 E 112TH PL      2012-01-19               Fail
     1444218.0              2 E 112TH PL               2 E 112TH PL      2012-01-26               Pass
     1444218.0               2 E 112TH PL              2 E 112TH PL      2013-01-10               Fail
     1444218.0              2 E 112TH PL               2 E 112TH PL      2013-01-17               Pass
     1444218.0              2 E 112TH PL               2 E 112TH PL      2014-04-08               Pass
     1444218.0              2 E 112TH PL               2 E 112TH PL      2014-09-10               Pass
     1444218.0              2 E 112TH PL               2 E 112TH PL      2015-07-17               Fail
     1444218.0              2 E 112TH PL               2 E 112TH PL      2015-07-24               Pass
     1444218.0              2 E 112TH PL               2 E 112TH PL      2016-02-04               Fail
     1444218.0              2 E 112TH PL               2 E 112TH PL      2016-02-11 Pass w/ Conditions
     1444218.0              2 E 112TH PL               2 E 112TH PL      2017-01-30 Pass w/ Conditions
     1444218.0              2 E 112TH PL               2 E 112TH PL      2018-06-21 Pass w/ Conditions
     1444218.0              2 E 112TH PL               2 E 112TH PL      2019-04-04 Pass w/ Conditions

In [20]:
# Get the remaining Restaurant_IDs that have multiple normalized addresses
multi_address_ids_normalized = (
    id_address_normalized_counts[
        id_address_normalized_counts > 1
    ].index
)

# Get unique address variants for those IDs
address_variants = (
    df[df["Restaurant_ID"].isin(multi_address_ids_normalized)]
    [["Restaurant_ID", "Address_normalized"]]
    .drop_duplicates()
    .sort_values(["Restaurant_ID", "Address_normalized"])
)

print("Number of unique Restaurant_ID + address combinations:",
      len(address_variants))

print("\nFirst 100 address variants:")
print(address_variants.head(100).to_string(index=False))

Number of unique Restaurant_ID + address combinations: 151

First 100 address variants:
 Restaurant_ID         Address_normalized
        1975.0      5308-5312 N MILWAUKEE
        1975.0  5308-5312 N MILWAUKEE AVE
       14616.0                333 W 35 ST
       14616.0              333 W 35TH ST
       14616.0         333 W 35TH ST BLDG
       23120.0             251 E HURON ST
       23120.0             257 E HURON ST
       41725.0            3323 W 111TH ST
       41725.0            3333 W 111TH ST
       80130.0            111 E WACKER DR
       80130.0         179 W VAN BUREN ST
       80153.0             165 E HURON ST
       80153.0          676 N ST CLAIR ST
       81030.0      1453 E HYDE PARK BLVD
       81030.0      1461 E HYDE PARK BLVD
     1042276.0         2809 N ASHLAND AVE
     1042276.0         2825 N ASHLAND AVE
     1045301.0         1400 W RANDOLPH ST
     1045301.0            160 N LOOMIS ST
     1093945.0        2321 W LAWRENCE AVE
     1093945.0        2321 W LAWRENSE AVE
     1142125.0          5700 S CICERO AVE
     1142125.0          5800 S CICERO AVE
     1443483.0       4742-44 N RACINE AVE
     1443483.0     4742-4744 N RACINE AVE
     1444218.0              2 E 112 TH ST
     1444218.0               2 E 112TH PL
     1473356.0          231 N ASHLAND AVE
     1473356.0          235 N ASHLAND AVE
     1573356.0           46 E CHICAGO AVE
     1573356.0            46 E CHICAGO ST
     1743553.0       150 E RANDOLPH ST FL
     1743553.0         150 N MICHIGAN AVE
     1816680.0            1642 W 79 ST FL
     1816680.0    8601 S STONY ISLAND AVE
     1909538.0              11601 W TOUHY
     1909538.0          11601 W TOUHY AVE
     1933748.0            5400 N CLARK ST
     1933748.0       5400-5402 N CLARK ST
     1937822.0          2717 N ELSTON AVE
     1937822.0          2739 N ELSTON AVE
     1942312.0          1120 W WILSON AVE
     1942312.0     1120-1122 W WILSON AVE
     1947810.0          101 N WESTERN AVE
     1947810.0      101-111 N WESTERN AVE
     1964839.0         500 N MICHIGAN AVE
     1964839.0         520 N MICHIGAN AVE
     1968904.0           2401 W DEVON AVE
     1968904.0      2401-2405 W DEVON AVE
     1997579.0      6344 W IRVING PARK RD
     1997579.0 6344-6348 W IRVING PARK RD
     1998392.0         4138 N LINCOLN AVE
     1998392.0        4138-4142 N LINCOLN
     2003847.0      1328-1330 W MORSE AVE
     2003847.0           1330 W MORSE AVE
     2009231.0    11919 S AVENUE O AVE FL
     2009231.0  11919 S AVENUE O AVE FRNT
     2060665.0    4310-4312 S PRAIRIE AVE
     2060665.0    4310-4314 S PRAIRIE AVE
     2069775.0              1151 W TAYLOR
     2069775.0      1151-1161 W TAYLOR ST
     2098830.0           2039 W NORTH AVE
     2098830.0      2039-2041 W NORTH AVE
     2098831.0           2039 W NORTH AVE
     2098831.0      2039-2041 W NORTH AVE
     2124632.0   3941-3943 W LAWRENCE AVE
     2124632.0        3943 W LAWRENCE AVE
     2125423.0          208-210 W 87TH ST
     2125423.0              210 W 87TH ST
     2141813.0            201 E GRAND AVE
     2141813.0        201-205 E GRAND AVE
     2142351.0             201 N STATE ST
     2142351.0          201 N STATE ST FL
     2146635.0          3927 N HARLEM AVE
     2146635.0          3937 N HARLEM AVE
     2152257.0             1646 W 95TH ST
     2152257.0        1646-1648 W 95TH ST
     2152726.0         8308 S ASHLAND AVE
     2152726.0    8308-8310 S ASHLAND AVE
     2152981.0         37 S WABASH AVE FL
     2152981.0         37-39 S WABASH AVE
     2157629.0  4713-4717 W FULLERTON AVE
     2157629.0       4715 W FULLERTON AVE
     2158267.0           10000 S AVENUE L
     2158267.0       3553-3559 E 100TH ST
     2192579.0            2031 N CLYBOURN
     2192579.0        2031 N CLYBOURN AVE
     2196808.0          6038 S PULASKI RD
     2196808.0     6038-6040 S PULASKI RD
     2232394.0     2923-2925 N HALSTED ST
     2232394.0          2925 N HALSTED ST
     2252464.0            2827 N BROADWAY
     2252464.0       2827-2831 N BROADWAY
     2283546.0        305 E GARFIELD BLVD
     2283546.0         305-307 E GARFIELD
     2290163.0          335 S FRANKLIN ST
     2290163.0          337 S FRANKLIN ST
     2373706.0             1644 W 95TH ST
     2373706.0        1646-1648 W 95TH ST
     2391012.0        1500 N CLYBOURN AVE

In [21]:
# Find address pairs where one address is exactly the other
# with an additional common street-type suffix.

street_types = {
    "ST", "AVE", "RD", "DR", "BLVD",
    "PL", "PKWY", "PLZ", "HWY", "CT"
}

suffix_variants = []

for restaurant_id, group in (
    address_variants.groupby("Restaurant_ID")
):
    addresses = group["Address_normalized"].tolist()

    for address in addresses:
        parts = address.split()

        if not parts:
            continue

        last_token = parts[-1]

        if last_token in street_types:
            shorter = " ".join(parts[:-1])

            if shorter in addresses:
                suffix_variants.append(
                    {
                        "Restaurant_ID": restaurant_id,
                        "Shorter_address": shorter,
                        "Full_address": address,
                        "Suffix": last_token
                    }
                )

suffix_variants_df = pd.DataFrame(suffix_variants)

print("Potential omitted street-suffix cases:",
      len(suffix_variants_df))

print("\nCases found:")
print(suffix_variants_df.to_string(index=False))

Potential omitted street-suffix cases: 3

Cases found:
 Restaurant_ID       Shorter_address              Full_address Suffix
        1975.0 5308-5312 N MILWAUKEE 5308-5312 N MILWAUKEE AVE    AVE
     1909538.0         11601 W TOUHY         11601 W TOUHY AVE    AVE
     2192579.0       2031 N CLYBOURN       2031 N CLYBOURN AVE    AVE

In [22]:
inspect_ids = [1975.0, 1909538.0, 2192579.0]

suffix_inspection_history = (
    df[
        df["Restaurant_ID"].isin(inspect_ids)
    ][
        [
            "Restaurant_ID",
            "Address",
            "Address_normalized",
            "Inspection Date",
            "Inspection Type",
            "Results"
        ]
    ]
    .sort_values(
        ["Restaurant_ID", "Inspection Date"]
    )
)

print(
    suffix_inspection_history.to_string(index=False)
)

 Restaurant_ID                    Address        Address_normalized Inspection Date          Inspection Type            Results
        1975.0 5308-5312 N MILWAUKEE AVE  5308-5312 N MILWAUKEE AVE      2010-08-30                Complaint               Fail
        1975.0 5308-5312 N MILWAUKEE AVE  5308-5312 N MILWAUKEE AVE      2010-09-01  Complaint Re-Inspection               Fail
        1975.0 5308-5312 N MILWAUKEE AVE  5308-5312 N MILWAUKEE AVE      2010-09-03  Complaint Re-Inspection               Pass
        1975.0 5308-5312 N MILWAUKEE AVE  5308-5312 N MILWAUKEE AVE      2010-10-19     Short Form Complaint               Pass
        1975.0 5308-5312 N MILWAUKEE AVE  5308-5312 N MILWAUKEE AVE      2011-02-25                Complaint               Pass
        1975.0 5308-5312 N MILWAUKEE AVE  5308-5312 N MILWAUKEE AVE      2011-05-06 Suspected Food Poisoning               Pass
        1975.0 5308-5312 N MILWAUKEE AVE  5308-5312 N MILWAUKEE AVE      2011-06-23     Short Form Complaint               Pass
        1975.0     5308-5312 N MILWAUKEE      5308-5312 N MILWAUKEE      2012-01-27                  Canvass               Pass
     1909538.0         11601 W TOUHY AVE          11601 W TOUHY AVE      2010-06-16                  Canvass               Pass
     1909538.0         11601 W TOUHY AVE          11601 W TOUHY AVE      2011-06-23                  Canvass               Pass
     1909538.0         11601 W TOUHY AVE          11601 W TOUHY AVE      2012-11-07                  Canvass               Pass
     1909538.0         11601 W TOUHY AVE          11601 W TOUHY AVE      2013-09-17                  Canvass               Pass
     1909538.0         11601 W TOUHY AVE          11601 W TOUHY AVE      2014-07-24                  Canvass               Pass
     1909538.0         11601 W TOUHY AVE          11601 W TOUHY AVE      2015-01-23                  Canvass               Pass
     1909538.0         11601 W TOUHY AVE          11601 W TOUHY AVE      2016-02-23                  Canvass               Pass
     1909538.0         11601 W TOUHY AVE          11601 W TOUHY AVE      2017-07-07                  Canvass               Pass
     1909538.0         11601 W TOUHY AVE          11601 W TOUHY AVE      2018-01-11                  Canvass               Pass
     1909538.0         11601 W TOUHY AVE          11601 W TOUHY AVE      2019-04-08                  Canvass               Pass
     1909538.0          11601 W TOUHY AVE         11601 W TOUHY AVE      2020-01-24                  Canvass               Pass
     1909538.0              11601 W TOUHY             11601 W TOUHY      2024-02-26                  Canvass               Pass
     1909538.0              11601 W TOUHY             11601 W TOUHY      2024-11-06                  Canvass               Pass
     1909538.0              11601 W TOUHY             11601 W TOUHY      2025-10-03                  Canvass               Pass
     1909538.0              11601 W TOUHY             11601 W TOUHY      2026-03-25                  Canvass               Pass
     2192579.0           2031 N CLYBOURN            2031 N CLYBOURN      2013-05-15                  License               Pass
     2192579.0       2031 N CLYBOURN AVE        2031 N CLYBOURN AVE      2014-10-01                  Canvass Pass w/ Conditions
     2192579.0       2031 N CLYBOURN AVE        2031 N CLYBOURN AVE      2015-11-10                  Canvass Pass w/ Conditions
     2192579.0       2031 N CLYBOURN AVE        2031 N CLYBOURN AVE      2015-11-13    Canvass Re-Inspection               Pass
     2192579.0       2031 N CLYBOURN AVE        2031 N CLYBOURN AVE      2016-07-22                  Canvass               Fail
     2192579.0       2031 N CLYBOURN AVE        2031 N CLYBOURN AVE      2016-07-29    Canvass Re-Inspection               Pass

In [23]:
from difflib import SequenceMatcher

address_pairs = []

for restaurant_id, group in address_variants.groupby("Restaurant_ID"):
    addresses = group["Address_normalized"].tolist()

    if len(addresses) < 2:
        continue

    for i in range(len(addresses)):
        for j in range(i + 1, len(addresses)):
            a = addresses[i]
            b = addresses[j]

            similarity = SequenceMatcher(
                None, a, b
            ).ratio()

            address_pairs.append({
                "Restaurant_ID": restaurant_id,
                "Address_1": a,
                "Address_2": b,
                "Similarity": similarity
            })

address_similarity_df = pd.DataFrame(address_pairs)

address_similarity_df = (
    address_similarity_df
    .sort_values(
        ["Similarity", "Restaurant_ID"],
        ascending=[False, True]
    )
    .reset_index(drop=True)
)

print("Address pairs:", len(address_similarity_df))

print(
    address_similarity_df[
        address_similarity_df["Similarity"] >= 0.80
    ].to_string(index=False)
)

Address pairs: 77
 Restaurant_ID                 Address_1                  Address_2  Similarity
     2397933.0 6703-6707 N NORTHWEST HWY  6705-6707 N NORTHWEST HWY    0.960000
     2060665.0   4310-4312 S PRAIRIE AVE    4310-4314 S PRAIRIE AVE    0.956522
     2641388.0   6700 S STONY ISLAND AVE    6720 S STONY ISLAND AVE    0.956522
     2452283.0    2856-2860 N HALSTED ST     2858-2860 N HALSTED ST    0.954545
     1443483.0      4742-44 N RACINE AVE     4742-4744 N RACINE AVE    0.952381
     1093945.0       2321 W LAWRENCE AVE        2321 W LAWRENSE AVE    0.947368
     1964839.0        500 N MICHIGAN AVE         520 N MICHIGAN AVE    0.944444
     1142125.0         5700 S CICERO AVE          5800 S CICERO AVE    0.941176
     1473356.0         231 N ASHLAND AVE          235 N ASHLAND AVE    0.941176
     2146635.0         3927 N HARLEM AVE          3937 N HARLEM AVE    0.941176
     2290163.0         335 S FRANKLIN ST          337 S FRANKLIN ST    0.941176
     2551263.0         4230 S ARCHER AVE          4232 S ARCHER AVE    0.941176
     2609815.0         1025 W ADDISON ST          1027 W ADDISON ST    0.941176
     2917578.0         1025 W ADDISON ST          1027 W ADDISON ST    0.941176
       41725.0           3323 W 111TH ST            3333 W 111TH ST    0.933333
       23120.0            251 E HURON ST             257 E HURON ST    0.928571
     2428634.0            515 N STATE ST             521 N STATE ST    0.928571
     2776230.0 2323-2357 S WENTWORTH AVE  2325-2359 S WENTWORTH AVE    0.920000
       14616.0               333 W 35 ST              333 W 35TH ST    0.916667
     2009231.0   11919 S AVENUE O AVE FL  11919 S AVENUE O AVE FRNT    0.916667
        1975.0     5308-5312 N MILWAUKEE  5308-5312 N MILWAUKEE AVE    0.913043
       81030.0     1453 E HYDE PARK BLVD      1461 E HYDE PARK BLVD    0.904762
     2142351.0            201 N STATE ST          201 N STATE ST FL    0.903226
     1947810.0         101 N WESTERN AVE      101-111 N WESTERN AVE    0.894737
     2846261.0     842-844 W RANDOLPH ST          844 W RANDOLPH ST    0.894737
     1997579.0     6344 W IRVING PARK RD 6344-6348 W IRVING PARK RD    0.893617
     1042276.0        2809 N ASHLAND AVE         2825 N ASHLAND AVE    0.888889
     2528207.0        151 N MICHIGAN AVE         189 N MICHIGAN AVE    0.888889
     2124632.0  3941-3943 W LAWRENCE AVE        3943 W LAWRENCE AVE    0.883721
     1937822.0         2717 N ELSTON AVE          2739 N ELSTON AVE    0.882353
     2141813.0           201 E GRAND AVE        201-205 E GRAND AVE    0.882353
     2192579.0           2031 N CLYBOURN        2031 N CLYBOURN AVE    0.882353
     2405946.0         5456 N HARLEM AVE          5472 N HARLEM AVE    0.882353
     2670642.0         1017 W ADDISON ST          1025 W ADDISON ST    0.882353
     2152726.0        8308 S ASHLAND AVE    8308-8310 S ASHLAND AVE    0.878049
     1942312.0         1120 W WILSON AVE     1120-1122 W WILSON AVE    0.871795
     2196808.0         6038 S PULASKI RD     6038-6040 S PULASKI RD    0.871795
     2232394.0    2923-2925 N HALSTED ST          2925 N HALSTED ST    0.871795
     2589451.0    7547-7549 S CICERO AVE          7549 S CICERO AVE    0.871795
     2641992.0         1745 N HARLEM AVE     1745-1747 N HARLEM AVE    0.871795
     1909538.0             11601 W TOUHY          11601 W TOUHY AVE    0.866667
     2125423.0         208-210 W 87TH ST              210 W 87TH ST    0.866667
     2433121.0             400 E 83RD ST          400-404 E 83RD ST    0.866667
     1968904.0          2401 W DEVON AVE      2401-2405 W DEVON AVE    0.864865
     2003847.0     1328-1330 W MORSE AVE           1330 W MORSE AVE    0.864865
     2098830.0          2039 W NORTH AVE      2039-2041 W NORTH AVE    0.864865
     2098831.0          2039 W NORTH AVE      2039-2041 W NORTH AVE    0.864865
     1933748.0           5400 N CLARK ST       5400-5402 N CLARK ST    0.857143
     2252464.0           2827 N BROADWAY       2827-2831 N BROADWAY    0.857143
     2152257.0            1646 W 95TH ST        1646-1648 W 95TH ST    0.848485
     2373706.0            1644 W 95TH ST        1646-1648 W 95TH ST    0.848485
     2157629.0 4713-4717 W FULLERTON AVE       4715 W FULLERTON AVE    0.844444
       14616.0             333 W 35TH ST         333 W 35TH ST BLDG    0.838710
     1573356.0          46 E CHICAGO AVE            46 E CHICAGO ST    0.838710
     2152981.0        37 S WABASH AVE FL         37-39 S WABASH AVE    0.833333
     2398745.0    2129-2139 S ARCHER AVE          2131 S ARCHER AVE    0.820513
     1444218.0             2 E 112 TH ST               2 E 112TH PL    0.800000

In [24]:
text_variant_ids = [14616.0, 1093945.0, 1573356.0, 1444218.0]

text_variant_history = (
    df[
        df["Restaurant_ID"].isin(text_variant_ids)
    ][
        [
            "Restaurant_ID",
            "Address",
            "Address_normalized",
            "Inspection Date",
            "Inspection Type",
            "Results"
        ]
    ]
    .sort_values(
        ["Restaurant_ID", "Inspection Date"]
    )
)

print(
    text_variant_history.to_string(index=False)
)

 Restaurant_ID             Address  Address_normalized Inspection Date       Inspection Type            Results
       14616.0        333 W 35 ST          333 W 35 ST      2010-03-25               Canvass               Pass
       14616.0      333 W 35TH ST        333 W 35TH ST      2010-03-25               Canvass               Pass
       14616.0      333 W 35TH ST        333 W 35TH ST      2010-03-25               Canvass Pass w/ Conditions
       14616.0      333 W 35TH ST        333 W 35TH ST      2010-03-25               Canvass               Pass
       14616.0      333 W 35TH ST        333 W 35TH ST      2010-03-25               Canvass               Pass
       14616.0      333 W 35TH ST        333 W 35TH ST      2010-03-25               Canvass Pass w/ Conditions
       14616.0      333 W 35TH ST        333 W 35TH ST      2010-03-25               Canvass               Pass
       14616.0      333 W 35TH ST        333 W 35TH ST      2010-03-25               Canvass               Pass
       14616.0      333 W 35TH ST        333 W 35TH ST      2010-03-26               Canvass               Pass
       14616.0      333 W 35TH ST        333 W 35TH ST      2010-04-02               Canvass               Pass
       14616.0      333 W 35TH ST        333 W 35TH ST      2011-03-28               Canvass               Pass
       14616.0      333 W 35TH ST        333 W 35TH ST      2011-03-28               Canvass Pass w/ Conditions
       14616.0      333 W 35TH ST        333 W 35TH ST      2011-03-28               Canvass               Pass
       14616.0      333 W 35TH ST        333 W 35TH ST      2011-03-28               Canvass               Pass
       14616.0      333 W 35TH ST        333 W 35TH ST      2011-03-28               Canvass               Pass
       14616.0      333 W 35TH ST        333 W 35TH ST      2011-03-28               Canvass               Fail
       14616.0      333 W 35TH ST        333 W 35TH ST      2011-03-28               Canvass               Pass
       14616.0      333 W 35TH ST        333 W 35TH ST      2011-03-28               Canvass               Pass
       14616.0      333 W 35TH ST        333 W 35TH ST      2011-03-28               Canvass               Fail
       14616.0      333 W 35TH ST        333 W 35TH ST      2011-03-28               Canvass Pass w/ Conditions
       14616.0      333 W 35TH ST        333 W 35TH ST      2011-03-28               Canvass               Pass
       14616.0      333 W 35TH ST        333 W 35TH ST      2011-03-28               Canvass               Pass
       14616.0      333 W 35TH ST        333 W 35TH ST      2011-03-28               Canvass               Pass
       14616.0      333 W 35TH ST        333 W 35TH ST      2011-03-28               Canvass               Pass
       14616.0      333 W 35TH ST        333 W 35TH ST      2011-03-28               Canvass Pass w/ Conditions
       14616.0 333 W 35TH ST BLDG   333 W 35TH ST BLDG      2011-03-28               Canvass               Pass
       14616.0      333 W 35TH ST        333 W 35TH ST      2011-03-30 Canvass Re-Inspection               Pass
       14616.0      333 W 35TH ST        333 W 35TH ST      2011-08-31  Short Form Complaint Pass w/ Conditions
     1093945.0 2321 W LAWRENSE AVE 2321 W LAWRENSE AVE      2010-12-27               Canvass Pass w/ Conditions
     1093945.0 2321 W LAWRENCE AVE 2321 W LAWRENCE AVE      2012-02-16               Canvass Pass w/ Conditions
     1444218.0      2 E 112 TH ST        2 E 112 TH ST      2010-05-17               Canvass               Pass
     1444218.0       2 E 112TH PL         2 E 112TH PL      2012-01-19               Canvass               Fail
     1444218.0       2 E 112TH PL         2 E 112TH PL      2012-01-26 Canvass Re-Inspection               Pass
     1444218.0        2 E 112TH PL        2 E 112TH PL      2013-01-10               Canvass               Fail
     1444218.0       2 E 112TH PL         2 E 112TH PL      2013-01-17 Canvass Re-Inspection               Pass
     1444218.0       2 E 112TH PL         2 E 112TH PL      2014-04-08               Canvass               Pass
     1444218.0       2 E 112TH PL         2 E 112TH PL      2014-09-10             Complaint               Pass
     1444218.0       2 E 112TH PL         2 E 112TH PL      2015-07-17               Canvass               Fail
     1444218.0       2 E 112TH PL         2 E 112TH PL      2015-07-24 Canvass Re-Inspection               Pass
     1444218.0       2 E 112TH PL         2 E 112TH PL      2016-02-04               Canvass               Fail
     1444218.0       2 E 112TH PL         2 E 112TH PL      2016-02-11 Canvass Re-Inspection Pass w/ Conditions
     1444218.0       2 E 112TH PL         2 E 112TH PL      2017-01-30               Canvass Pass w/ Conditions
     1444218.0       2 E 112TH PL         2 E 112TH PL      2018-06-21               Canvass Pass w/ Conditions
     1444218.0       2 E 112TH PL         2 E 112TH PL      2019-04-04               Canvass Pass w/ Conditions
     1444218.0       2 E 112TH PL         2 E 112TH PL      2020-03-10               Canvass Pass w/ Conditions
     1444218.0       2 E 112TH PL         2 E 112TH PL      2021-01-08               Canvass               Pass
     1444218.0       2 E 112TH PL         2 E 112TH PL      2022-02-23               Canvass               Fail
     1444218.0       2 E 112TH PL         2 E 112TH PL      2022-03-02 Canvass Re-Inspection               Fail
     1444218.0       2 E 112TH PL         2 E 112TH PL      2022-03-09 Canvass Re-Inspection               Pass
     1444218.0       2 E 112TH PL         2 E 112TH PL      2023-08-11               Canvass               Pass
     1444218.0       2 E 112TH PL         2 E 112TH PL      2023-10-20  Short Form Complaint               Pass
     1444218.0       2 E 112TH PL         2 E 112TH PL      2024-07-10               Canvass               Pass
     1444218.0        2 E 112TH PL        2 E 112TH PL      2025-02-24               Canvass               Pass
     1444218.0        2 E 112TH PL        2 E 112TH PL      2025-11-26             Complaint               Pass
     1444218.0        2 E 112TH PL        2 E 112TH PL      2026-05-01               Canvass               Pass
     1573356.0   46 E CHICAGO AVE     46 E CHICAGO AVE      2011-06-07             Complaint               Pass
     1573356.0   46 E CHICAGO AVE     46 E CHICAGO AVE      2013-08-12               Canvass               Pass
     1573356.0   46 E CHICAGO AVE     46 E CHICAGO AVE      2014-10-09               Canvass               Pass
     1573356.0   46 E CHICAGO AVE     46 E CHICAGO AVE      2015-11-24               Canvass               Fail
     1573356.0   46 E CHICAGO AVE     46 E CHICAGO AVE      2015-12-21 Canvass Re-Inspection               Pass
     1573356.0   46 E CHICAGO AVE     46 E CHICAGO AVE      2016-06-23             Complaint               Pass
     1573356.0   46 E CHICAGO AVE     46 E CHICAGO AVE      2017-06-14               Canvass Pass w/ Conditions
     1573356.0   46 E CHICAGO AVE     46 E CHICAGO AVE      2018-06-06             Complaint Pass w/ Conditions
     1573356.0    46 E CHICAGO ST      46 E CHICAGO ST      2019-08-13               Canvass Pass w/ Conditions

In [25]:
range_variant_ids = [
    1443483.0,
    2060665.0,
    2397933.0,
    2452283.0,
    2776230.0,
    1947810.0,
    1997579.0,
    2124632.0,
    2141813.0,
    2152726.0,
    2196808.0,
    2232394.0,
    2589451.0,
    2641992.0,
    1933748.0,
    2252464.0,
    2152257.0,
    2003847.0,
    2098830.0,
    2125423.0,
    2433121.0
]

range_variant_history = (
    df[
        df["Restaurant_ID"].isin(range_variant_ids)
    ][
        [
            "Restaurant_ID",
            "Address",
            "Address_normalized",
            "Inspection Date",
            "Inspection Type",
            "Results"
        ]
    ]
    .sort_values(
        ["Restaurant_ID", "Inspection Date"]
    )
)

print(
    range_variant_history.to_string(index=False)
)

 Restaurant_ID                     Address         Address_normalized Inspection Date         Inspection Type            Results
     1443483.0       4742-44 N RACINE AVE        4742-44 N RACINE AVE      2011-01-25                 Canvass               Fail
     1443483.0       4742-44 N RACINE AVE        4742-44 N RACINE AVE      2011-02-17   Canvass Re-Inspection               Pass
     1443483.0     4742-4744 N RACINE AVE      4742-4744 N RACINE AVE      2012-04-25                 Canvass               Pass
     1443483.0     4742-4744 N RACINE AVE      4742-4744 N RACINE AVE      2013-06-18                 Canvass               Pass
     1443483.0     4742-4744 N RACINE AVE      4742-4744 N RACINE AVE      2014-04-28                 Canvass Pass w/ Conditions
     1443483.0     4742-4744 N RACINE AVE      4742-4744 N RACINE AVE      2015-04-21                 Canvass               Pass
     1443483.0     4742-4744 N RACINE AVE      4742-4744 N RACINE AVE      2015-11-16                 Canvass               Pass
     1443483.0     4742-4744 N RACINE AVE      4742-4744 N RACINE AVE      2016-08-29                 Canvass               Pass
     1443483.0     4742-4744 N RACINE AVE      4742-4744 N RACINE AVE      2017-08-15                 Canvass Pass w/ Conditions
     1443483.0     4742-4744 N RACINE AVE      4742-4744 N RACINE AVE      2017-09-06   Canvass Re-Inspection               Pass
     1443483.0     4742-4744 N RACINE AVE      4742-4744 N RACINE AVE      2018-09-20                 Canvass Pass w/ Conditions
     1443483.0      4742-4744 N RACINE AVE     4742-4744 N RACINE AVE      2019-10-25                 Canvass Pass w/ Conditions
     1443483.0      4742-4744 N RACINE AVE     4742-4744 N RACINE AVE      2021-05-04                 Canvass               Pass
     1443483.0     4742-4744 N RACINE AVE      4742-4744 N RACINE AVE      2022-06-13                 Canvass               Pass
     1443483.0     4742-4744 N RACINE AVE      4742-4744 N RACINE AVE      2023-03-13                 Canvass               Pass
     1443483.0     4742-4744 N RACINE AVE      4742-4744 N RACINE AVE      2024-07-05                 Canvass Pass w/ Conditions
     1443483.0      4742-4744 N RACINE AVE     4742-4744 N RACINE AVE      2025-05-29                 Canvass               Pass
     1443483.0      4742-4744 N RACINE AVE     4742-4744 N RACINE AVE      2026-07-06                 Canvass               Pass
     1933748.0        5400-5402 N CLARK ST       5400-5402 N CLARK ST      2010-06-01                 Canvass Pass w/ Conditions
     1933748.0       5400-5402 N CLARK ST        5400-5402 N CLARK ST      2010-12-03                     SFP               Fail
     1933748.0            5400 N CLARK ST             5400 N CLARK ST      2011-05-23                 Canvass               Pass
     1933748.0       5400-5402 N CLARK ST        5400-5402 N CLARK ST      2012-10-01               Complaint               Fail
     1933748.0       5400-5402 N CLARK ST        5400-5402 N CLARK ST      2012-10-09 Complaint Re-Inspection               Pass
     1933748.0       5400-5402 N CLARK ST        5400-5402 N CLARK ST      2013-05-07                 Canvass               Pass
     1933748.0       5400-5402 N CLARK ST        5400-5402 N CLARK ST      2014-04-14                 Canvass               Fail
     1933748.0       5400-5402 N CLARK ST        5400-5402 N CLARK ST      2014-04-23   Canvass Re-Inspection               Pass
     1933748.0       5400-5402 N CLARK ST        5400-5402 N CLARK ST      2014-08-14               Complaint               Fail
     1933748.0        5400-5402 N CLARK ST       5400-5402 N CLARK ST      2015-03-16               Complaint               Fail
     1933748.0       5400-5402 N CLARK ST        5400-5402 N CLARK ST      2015-03-19 Complaint Re-Inspection               Fail
     1933748.0       5400-5402 N CLARK ST        5400-5402 N CLARK ST      2015-04-29    Short Form Complaint               Fail
     1933748.0       5400-5402 N CLARK ST        5400-5402 N CLARK ST      2015-07-31               Complaint               Fail
     1947810.0      101-111 N WESTERN AVE       101-111 N WESTERN AVE      2010-11-04               Complaint Pass w/ Conditions
     1947810.0      101-111 N WESTERN AVE       101-111 N WESTERN AVE      2012-01-10                 Canvass Pass w/ Conditions
     1947810.0      101-111 N WESTERN AVE       101-111 N WESTERN AVE      2013-10-29               Complaint               Pass
     1947810.0      101-111 N WESTERN AVE       101-111 N WESTERN AVE      2014-05-27                 Canvass Pass w/ Conditions
     1947810.0          101 N WESTERN AVE           101 N WESTERN AVE      2015-11-06                 Canvass Pass w/ Conditions
     1947810.0          101 N WESTERN AVE           101 N WESTERN AVE      2016-06-01                 Canvass Pass w/ Conditions
     1947810.0          101 N WESTERN AVE           101 N WESTERN AVE      2019-08-20                 Canvass Pass w/ Conditions
     1947810.0          101 N WESTERN AVE           101 N WESTERN AVE      2020-05-19                 Canvass               Pass
     1947810.0          101 N WESTERN AVE           101 N WESTERN AVE      2023-03-14                 Canvass               Fail
     1947810.0           101 N WESTERN AVE          101 N WESTERN AVE      2024-12-19                 Canvass               Pass
     1997579.0      6344 W IRVING PARK RD       6344 W IRVING PARK RD      2010-03-04               Complaint               Pass
     1997579.0      6344 W IRVING PARK RD       6344 W IRVING PARK RD      2011-02-01                 Canvass               Pass
     1997579.0      6344 W IRVING PARK RD       6344 W IRVING PARK RD      2011-11-21                 Canvass               Pass
     1997579.0      6344 W IRVING PARK RD       6344 W IRVING PARK RD      2012-10-09                 Canvass               Fail
     1997579.0      6344 W IRVING PARK RD       6344 W IRVING PARK RD      2012-10-18   Canvass Re-Inspection               Pass
     1997579.0      6344 W IRVING PARK RD       6344 W IRVING PARK RD      2013-03-11                 Canvass               Pass
     1997579.0      6344 W IRVING PARK RD       6344 W IRVING PARK RD      2014-05-29               Complaint               Pass
     1997579.0       6344 W IRVING PARK RD      6344 W IRVING PARK RD      2015-03-24                 Canvass               Pass
     1997579.0      6344 W IRVING PARK RD       6344 W IRVING PARK RD      2015-07-20               Complaint               Pass
     1997579.0      6344 W IRVING PARK RD       6344 W IRVING PARK RD      2015-11-16               Complaint               Pass
     1997579.0      6344 W IRVING PARK RD       6344 W IRVING PARK RD      2016-03-08                 Canvass               Pass
     1997579.0 6344-6348 W IRVING PARK RD  6344-6348 W IRVING PARK RD      2016-04-22                 Canvass               Pass
     1997579.0 6344-6348 W IRVING PARK RD  6344-6348 W IRVING PARK RD      2016-11-21                 Canvass               Pass
     1997579.0  6344-6348 W IRVING PARK RD 6344-6348 W IRVING PARK RD      2017-07-10                 Canvass               Fail
     1997579.0 6344-6348 W IRVING PARK RD  6344-6348 W IRVING PARK RD      2019-04-19                 Canvass Pass w/ Conditions
     1997579.0  6344-6348 W IRVING PARK RD 6344-6348 W IRVING PARK RD      2020-01-31                 Canvass               Fail
     1997579.0 6344-6348 W IRVING PARK RD  6344-6348 W IRVING PARK RD      2020-02-07   Canvass Re-Inspection Pass w/ Conditions
     1997579.0 6344-6348 W IRVING PARK RD  6344-6348 W IRVING PARK RD      2020-11-02               Complaint               Pass
     1997579.0 6344-6348 W IRVING PARK RD  6344-6348 W IRVING PARK RD      2021-10-13                 Canvass               Pass
     1997579.0 6344-6348 W IRVING PARK RD  6344-6348 W IRVING PARK RD      2021-11-03    Short Form Complaint               Pass
     2003847.0      1328-1330 W MORSE AVE       1328-1330 W MORSE AVE      2010-01-14                 License               Fail
     2003847.0      1328-1330 W MORSE AVE       1328-1330 W MORSE AVE      2010-01-14                 License               Fail
     2003847.0      1328-1330 W MORSE AVE       1328-1330 W MORSE AVE      2010-11-26               Complaint               Pass
     2003847.0       1328-1330 W MORSE AVE      1328-1330 W MORSE AVE      2011-07-15                 Canvass Pass w/ Conditions
     2003847.0       1328-1330 W MORSE AVE      1328-1330 W MORSE AVE      2011-07-18             Tag Removal               Pass
     2003847.0      1328-1330 W MORSE AVE       1328-1330 W MORSE AVE      2012-07-03                 Canvass               Pass
     2003847.0      1328-1330 W MORSE AVE       1328-1330 W MORSE AVE      2013-07-11                 Canvass               Pass
     2003847.0      1328-1330 W MORSE AVE       1328-1330 W MORSE AVE      2014-07-10                 Canvass               Pass
     2003847.0      1328-1330 W MORSE AVE       1328-1330 W MORSE AVE      2014-07-10   Canvass Re-Inspection               Pass
     2003847.0      1328-1330 W MORSE AVE       1328-1330 W MORSE AVE      2014-09-16                 Canvass               Pass
     2003847.0      1328-1330 W MORSE AVE       1328-1330 W MORSE AVE      2015-08-18                 Canvass               Pass
     2003847.0      1328-1330 W MORSE AVE       1328-1330 W MORSE AVE      2016-05-24                 Canvass Pass w/ Conditions
     2003847.0           1330 W MORSE AVE            1330 W MORSE AVE      2017-06-27                 Canvass               Pass
     2003847.0           1330 W MORSE AVE            1330 W MORSE AVE      2018-06-14                 Canvass               Fail
     2003847.0           1330 W MORSE AVE            1330 W MORSE AVE      2018-06-19   Canvass Re-Inspection               Pass
     2060665.0    4310-4312 S PRAIRIE AVE     4310-4312 S PRAIRIE AVE      2011-06-14      License-Task Force               Fail
     2060665.0    4310-4312 S PRAIRIE AVE     4310-4312 S PRAIRIE AVE      2011-07-01   License Re-Inspection               Fail
     2060665.0    4310-4314 S PRAIRIE AVE     4310-4314 S PRAIRIE AVE      2013-12-05                 Canvass Pass w/ Conditions
     2098830.0           2039 W NORTH AVE            2039 W NORTH AVE      2012-05-22                 License               Fail
     2098830.0      2039-2041 W NORTH AVE       2039-2041 W NORTH AVE      2013-10-24                 Canvass               Pass
     2098830.0      2039-2041 W NORTH AVE       2039-2041 W NORTH AVE      2014-08-15                 Canvass               Pass
     2098830.0      2039-2041 W NORTH AVE       2039-2041 W NORTH AVE      2015-09-21                 Canvass Pass w/ Conditions
     2098830.0      2039-2041 W NORTH AVE       2039-2041 W NORTH AVE      2016-08-31                 Canvass Pass w/ Conditions
     2124632.0   3941-3943 W LAWRENCE AVE    3941-3943 W LAWRENCE AVE      2011-11-09                 License               Fail
     2124632.0   3941-3943 W LAWRENCE AVE    3941-3943 W LAWRENCE AVE      2013-02-06                 Canvass               Pass
     2124632.0    3941-3943 W LAWRENCE AVE   3941-3943 W LAWRENCE AVE      2014-01-10                 Canvass Pass w/ Conditions
     2124632.0   3941-3943 W LAWRENCE AVE    3941-3943 W LAWRENCE AVE      2014-10-03                 Canvass               Pass
     2124632.0   3941-3943 W LAWRENCE AVE    3941-3943 W LAWRENCE AVE      2015-04-09                 Canvass               Pass
     2124632.0   3941-3943 W LAWRENCE AVE    3941-3943 W LAWRENCE AVE      2016-10-07                 Canvass               Fail
     2124632.0   3941-3943 W LAWRENCE AVE    3941-3943 W LAWRENCE AVE      2016-10-18   Canvass Re-Inspection               Pass
     2124632.0   3941-3943 W LAWRENCE AVE    3941-3943 W LAWRENCE AVE      2017-01-30                 Canvass               Pass
     2124632.0   3941-3943 W LAWRENCE AVE    3941-3943 W LAWRENCE AVE      2018-01-10                 Canvass               Fail
     2124632.0   3941-3943 W LAWRENCE AVE    3941-3943 W LAWRENCE AVE      2018-01-18   Canvass Re-Inspection               Pass
     2124632.0    3941-3943 W LAWRENCE AVE   3941-3943 W LAWRENCE AVE      2020-09-08               Complaint Pass w/ Conditions
     2124632.0   3941-3943 W LAWRENCE AVE    3941-3943 W LAWRENCE AVE      2021-01-26               Complaint               Fail
     2124632.0   3941-3943 W LAWRENCE AVE    3941-3943 W LAWRENCE AVE      2021-02-02 Complaint Re-Inspection Pass w/ Conditions
     2124632.0    3941-3943 W LAWRENCE AVE   3941-3943 W LAWRENCE AVE      2022-09-02                 Canvass               Pass
     2124632.0   3941-3943 W LAWRENCE AVE    3941-3943 W LAWRENCE AVE      2023-12-04                 Canvass               Fail
     2124632.0   3941-3943 W LAWRENCE AVE    3941-3943 W LAWRENCE AVE      2023-12-18   Canvass Re-Inspection               Pass
     2124632.0    3941-3943 W LAWRENCE AVE   3941-3943 W LAWRENCE AVE      2024-12-03                 Canvass               Pass
     2124632.0    3941-3943 W LAWRENCE AVE   3941-3943 W LAWRENCE AVE      2025-10-27                 Canvass               Pass
     2124632.0         3943 W LAWRENCE AVE        3943 W LAWRENCE AVE      2026-07-14                 License Pass w/ Conditions
     2125423.0          208-210 W 87TH ST           208-210 W 87TH ST      2012-02-03                 License               Fail
     2125423.0          208-210 W 87TH ST           208-210 W 87TH ST      2012-02-09                 License               Pass
     2125423.0          208-210 W 87TH ST           208-210 W 87TH ST      2012-02-16    Short Form Complaint               Pass
     2125423.0          208-210 W 87TH ST           208-210 W 87TH ST      2013-02-07                 Canvass               Pass
     2125423.0              210 W 87TH ST               210 W 87TH ST      2015-01-08                 Canvass               Fail
     2125423.0              210 W 87TH ST               210 W 87TH ST      2015-01-15   Canvass Re-Inspection               Pass
     2141813.0            201 E GRAND AVE             201 E GRAND AVE      2012-04-04                 License               Pass
     2141813.0            201 E GRAND AVE             201 E GRAND AVE      2013-03-13                 Canvass               Pass
     2141813.0            201 E GRAND AVE             201 E GRAND AVE      2013-11-26                 Canvass Pass w/ Conditions
     2141813.0            201 E GRAND AVE             201 E GRAND AVE      2014-04-08                 Canvass               Pass
     2141813.0            201 E GRAND AVE             201 E GRAND AVE      2015-02-04               Complaint               Pass
     2141813.0            201 E GRAND AVE             201 E GRAND AVE      2015-05-05               Complaint               Pass
     2141813.0             201 E GRAND AVE            201 E GRAND AVE      2016-03-08                 Canvass               Fail
     2141813.0            201 E GRAND AVE             201 E GRAND AVE      2017-02-27                 Canvass               Fail
     2141813.0            201 E GRAND AVE             201 E GRAND AVE      2017-03-01   Canvass Re-Inspection               Pass
     2141813.0             201 E GRAND AVE            201 E GRAND AVE      2018-08-21                 Canvass Pass w/ Conditions
     2141813.0            201 E GRAND AVE             201 E GRAND AVE      2019-07-02                 Canvass               Pass
     2141813.0        201-205 E GRAND AVE         201-205 E GRAND AVE      2021-02-17                 Canvass Pass w/ Conditions
     2141813.0        201-205 E GRAND AVE         201-205 E GRAND AVE      2021-03-12    Short Form Complaint Pass w/ Conditions
     2141813.0        201-205 E GRAND AVE         201-205 E GRAND AVE      2021-06-15               Complaint               Fail
     2141813.0        201-205 E GRAND AVE         201-205 E GRAND AVE      2021-06-22 Complaint Re-Inspection               Pass
     2141813.0            201 E GRAND AVE             201 E GRAND AVE      2022-09-21                 Canvass Pass w/ Conditions
     2141813.0        201-205 E GRAND AVE         201-205 E GRAND AVE      2022-09-21                 Canvass Pass w/ Conditions
     2141813.0        201-205 E GRAND AVE         201-205 E GRAND AVE      2023-11-21                 Canvass               Pass
     2141813.0        201-205 E GRAND AVE         201-205 E GRAND AVE      2024-08-01                 Canvass               Pass
     2141813.0         201-205 E GRAND AVE        201-205 E GRAND AVE      2025-07-24                 Canvass               Fail
     2141813.0         201-205 E GRAND AVE        201-205 E GRAND AVE      2026-03-10                 Canvass               Pass
     2152257.0             1646 W 95TH ST              1646 W 95TH ST      2012-04-27                 License               Fail
     2152257.0        1646-1648 W 95TH ST         1646-1648 W 95TH ST      2012-05-04                 License               Pass
     2152257.0        1646-1648 W 95TH ST         1646-1648 W 95TH ST      2013-05-15                 Canvass               Pass
     2152257.0        1646-1648 W 95TH ST         1646-1648 W 95TH ST      2014-02-21               Complaint               Pass
     2152257.0        1646-1648 W 95TH ST         1646-1648 W 95TH ST      2014-12-29                 Canvass Pass w/ Conditions
     2152726.0         8308 S ASHLAND AVE          8308 S ASHLAND AVE      2012-05-01                 License               Pass
     2152726.0         8308 S ASHLAND AVE          8308 S ASHLAND AVE      2012-08-10               Complaint               Pass
     2152726.0         8308 S ASHLAND AVE          8308 S ASHLAND AVE      2012-11-20               Complaint               Pass
     2152726.0         8308 S ASHLAND AVE          8308 S ASHLAND AVE      2013-09-09                 Canvass               Pass
     2152726.0    8308-8310 S ASHLAND AVE     8308-8310 S ASHLAND AVE      2014-04-18                 Canvass               Pass
     2152726.0    8308-8310 S ASHLAND AVE     8308-8310 S ASHLAND AVE      2015-07-10                 Canvass               Pass
     2196808.0          6038 S PULASKI RD           6038 S PULASKI RD      2013-01-18                 License               Fail
     2196808.0          6038 S PULASKI RD           6038 S PULASKI RD      2014-05-22               Complaint               Pass
     2196808.0          6038 S PULASKI RD           6038 S PULASKI RD      2014-10-07               Complaint               Pass
     2196808.0          6038 S PULASKI RD           6038 S PULASKI RD      2015-07-06                 Canvass               Pass
     2196808.0          6038 S PULASKI RD           6038 S PULASKI RD      2016-01-08                 Canvass Pass w/ Conditions
     2196808.0          6038 S PULASKI RD           6038 S PULASKI RD      2016-04-25               Complaint               Pass
     2196808.0          6038 S PULASKI RD           6038 S PULASKI RD      2016-08-16               Complaint               Pass
     2196808.0     6038-6040 S PULASKI RD      6038-6040 S PULASKI RD      2017-07-06                 Canvass               Pass
     2196808.0     6038-6040 S PULASKI RD      6038-6040 S PULASKI RD      2017-08-10               Complaint               Pass
     2196808.0     6038-6040 S PULASKI RD      6038-6040 S PULASKI RD      2018-02-07               Complaint               Fail
     2196808.0     6038-6040 S PULASKI RD      6038-6040 S PULASKI RD      2018-02-13 Complaint Re-Inspection               Pass
     2196808.0     6038-6040 S PULASKI RD      6038-6040 S PULASKI RD      2019-03-26               Complaint Pass w/ Conditions
     2196808.0     6038-6040 S PULASKI RD      6038-6040 S PULASKI RD      2019-09-25               Complaint               Fail

In [26]:
multi_address_summary = (
    df[df["Restaurant_ID"].isin(multi_address_ids_normalized)]
    .groupby("Restaurant_ID")
    .agg(
        address_count=("Address_normalized", "nunique"),
        first_address=("Address_normalized", "first"),
        last_address=("Address_normalized", "last"),
        first_inspection=("Inspection Date", "min"),
        last_inspection=("Inspection Date", "max")
    )
    .reset_index()
    .sort_values("Restaurant_ID")
)

print("Restaurant_IDs with multiple normalized addresses:",
      len(multi_address_summary))

display(multi_address_summary)

Restaurant_IDs with multiple normalized addresses: 75

,Restaurant_ID,address_count,first_address,last_address,first_inspection,last_inspection
0,1975.0,2,5308-5312 N MILWAUKEE,5308-5312 N MILWAUKEE AVE,2010-08-30,2012-01-27
1,14616.0,3,333 W 35 ST,333 W 35TH ST BLDG,2010-03-25,2011-08-31
2,23120.0,2,251 E HURON ST,257 E HURON ST,2011-07-27,2023-12-26
3,41725.0,2,3323 W 111TH ST,3333 W 111TH ST,2010-09-17,2026-07-24
4,80130.0,2,111 E WACKER DR,179 W VAN BUREN ST,2010-09-01,2018-03-21
...,...,...,...,...,...,...
70,2776230.0,2,2323-2357 S WENTWORTH AVE,2325-2359 S WENTWORTH AVE,2021-03-16,2025-11-19
71,2846261.0,2,842-844 W RANDOLPH ST,844 W RANDOLPH ST,2022-07-19,2024-06-04
72,2917578.0,2,1025 W ADDISON ST,1027 W ADDISON ST,2023-07-11,2025-11-04
73,2983053.0,2,10000 W OHARE ST,11601 W TOUHY AVE,2026-07-28,2026-07-28
74,2983595.0,2,10000 W OHARE ST,11601 W TOUHY AVE,2024-08-07,2026-01-09

In [27]:
address_change_details = (
    df[df["Restaurant_ID"].isin(multi_address_ids_normalized)]
    [["Restaurant_ID", "Inspection Date", "Address_normalized"]]
    .drop_duplicates()
    .sort_values(["Restaurant_ID", "Inspection Date"])
)

display(address_change_details)

        Restaurant_ID Inspection Date         Address_normalized
1447           1975.0      2010-08-30  5308-5312 N MILWAUKEE AVE
1448           1975.0      2010-09-01  5308-5312 N MILWAUKEE AVE
1449           1975.0      2010-09-03  5308-5312 N MILWAUKEE AVE
1450           1975.0      2010-10-19  5308-5312 N MILWAUKEE AVE
1451           1975.0      2011-02-25  5308-5312 N MILWAUKEE AVE
...               ...             ...                        ...
154087      2983053.0      2026-07-28          11601 W TOUHY AVE
154200      2983595.0      2024-08-07           10000 W OHARE ST
154202      2983595.0      2024-08-07          11601 W TOUHY AVE
154201      2983595.0      2026-01-09           10000 W OHARE ST
154203      2983595.0      2026-01-09          11601 W TOUHY AVE

[887 rows x 3 columns]