In [2]:
import pandas as pd
import numpy as np

In [3]:
DATA_PATH = "../data/processed/restaurant_identity.csv"

df = pd.read_csv(
    DATA_PATH,
    low_memory=False
)

print("Dataset loaded successfully!")
print("Shape:", df.shape)

print("\nColumns:")
print(df.columns.tolist())

Dataset loaded successfully!
Shape: (156985, 14)

Columns:
['License', 'Facility Type', 'Risk', 'Address', 'Inspection Date', 'Inspection Type', 'Results', 'Violations', 'Location', 'Latitude', 'Longitude', 'Latitude_4dp', 'Longitude_4dp', 'Restaurant_ID']

In [4]:
df.head()

,License,Facility Type,Risk,Address,Inspection Date,Inspection Type,Results,Violations,Location,Latitude,Longitude,Latitude_4dp,Longitude_4dp,Restaurant_ID
0,2.0,Restaurant,Risk 1 (High),230 W MONROE ST,2012-03-19,Canvass,Pass w/ Conditions,4. SOURCE OF CROSS CONTAMINATION CONTROLLED I....,"(41.88075715864721, -87.6347092983425)",41.880757,-87.634709,41.8808,-87.6347,1
1,2.0,Restaurant,Risk 1 (High),230 W MONROE ST,2010-06-15,Canvass,Pass,32. FOOD AND NON-FOOD CONTACT SURFACES PROPERL...,"(41.88075715864721, -87.6347092983425)",41.880757,-87.634709,41.8808,-87.6347,1
2,2.0,Restaurant,Risk 1 (High),230 W MONROE ST,2011-02-15,Canvass,Pass,32. FOOD AND NON-FOOD CONTACT SURFACES PROPERL...,"(41.88075715864721, -87.6347092983425)",41.880757,-87.634709,41.8808,-87.6347,1
3,2.0,Restaurant,Risk 1 (High),230 W MONROE ST,2013-07-19,Canvass,Pass,32. FOOD AND NON-FOOD CONTACT SURFACES PROPERL...,"(41.88075715864721, -87.6347092983425)",41.880757,-87.634709,41.8808,-87.6347,1
4,2.0,Restaurant,Risk 1 (High),230 W MONROE ST,2014-04-18,Canvass,Pass,32. FOOD AND NON-FOOD CONTACT SURFACES PROPERL...,"(41.88075715864721, -87.6347092983425)",41.880757,-87.634709,41.8808,-87.6347,1

In [5]:
# Convert Inspection Date to datetime
df["Inspection Date"] = pd.to_datetime(
    df["Inspection Date"]
)

# Sort inspections chronologically for each restaurant
df = df.sort_values(
    ["Restaurant_ID", "Inspection Date"]
).reset_index(drop=True)

# Create inspection sequence starting from 0
df["Inspection_Sequence"] = (
    df.groupby("Restaurant_ID")
      .cumcount()
)

# Check the result
print(
    df[
        [
            "Restaurant_ID",
            "Inspection_Sequence",
            "Inspection Date",
            "Results"
        ]
    ].head(20)
)

    Restaurant_ID  Inspection_Sequence Inspection Date             Results
0               1                    0      2010-06-15                Pass
1               1                    1      2011-02-15                Pass
2               1                    2      2012-03-19  Pass w/ Conditions
3               1                    3      2013-07-19                Pass
4               1                    4      2014-04-18                Pass
5               1                    5      2014-11-20                Pass
6               1                    6      2015-04-21                Pass
7               1                    7      2015-12-14                Pass
8               1                    8      2016-03-22  Pass w/ Conditions
9               1                    9      2016-10-27                Fail
10              1                   10      2016-11-04                Pass
11              1                   11      2016-12-14  Pass w/ Conditions
12              1                   12      2017-05-12                Pass
13              1                   13      2018-02-13  Pass w/ Conditions
14              1                   14      2019-11-01  Pass w/ Conditions
15              2                    0      2010-07-15                Pass
16              2                    1      2011-06-01                Pass
17              2                    2      2012-06-14                Pass
18              2                    3      2013-08-22                Pass
19              2                    4      2013-12-16                Pass

In [6]:
df.head(10)

,License,Facility Type,Risk,Address,Inspection Date,Inspection Type,Results,Violations,Location,Latitude,Longitude,Latitude_4dp,Longitude_4dp,Restaurant_ID,Inspection_Sequence
0,2.0,Restaurant,Risk 1 (High),230 W MONROE ST,2010-06-15,Canvass,Pass,32. FOOD AND NON-FOOD CONTACT SURFACES PROPERL...,"(41.88075715864721, -87.6347092983425)",41.880757,-87.634709,41.8808,-87.6347,1,0
1,2.0,Restaurant,Risk 1 (High),230 W MONROE ST,2011-02-15,Canvass,Pass,32. FOOD AND NON-FOOD CONTACT SURFACES PROPERL...,"(41.88075715864721, -87.6347092983425)",41.880757,-87.634709,41.8808,-87.6347,1,1
2,2.0,Restaurant,Risk 1 (High),230 W MONROE ST,2012-03-19,Canvass,Pass w/ Conditions,4. SOURCE OF CROSS CONTAMINATION CONTROLLED I....,"(41.88075715864721, -87.6347092983425)",41.880757,-87.634709,41.8808,-87.6347,1,2
3,2.0,Restaurant,Risk 1 (High),230 W MONROE ST,2013-07-19,Canvass,Pass,32. FOOD AND NON-FOOD CONTACT SURFACES PROPERL...,"(41.88075715864721, -87.6347092983425)",41.880757,-87.634709,41.8808,-87.6347,1,3
4,2.0,Restaurant,Risk 1 (High),230 W MONROE ST,2014-04-18,Canvass,Pass,32. FOOD AND NON-FOOD CONTACT SURFACES PROPERL...,"(41.88075715864721, -87.6347092983425)",41.880757,-87.634709,41.8808,-87.6347,1,4
5,2.0,Restaurant,Risk 1 (High),230 W MONROE ST,2014-11-20,Canvass,Pass,31. CLEAN MULTI-USE UTENSILS AND SINGLE SERVIC...,"(41.88075715864721, -87.6347092983425)",41.880757,-87.634709,41.8808,-87.6347,1,5
6,2.0,Restaurant,Risk 1 (High),230 W MONROE ST,2015-04-21,Canvass,Pass,31. CLEAN MULTI-USE UTENSILS AND SINGLE SERVIC...,"(41.88075715864721, -87.6347092983425)",41.880757,-87.634709,41.8808,-87.6347,1,6
7,2.0,Restaurant,Risk 1 (High),230 W MONROE ST,2015-12-14,Complaint,Pass,33. FOOD AND NON-FOOD CONTACT EQUIPMENT UTENSI...,"(41.88075715864721, -87.6347092983425)",41.880757,-87.634709,41.8808,-87.6347,1,7
8,2.0,Restaurant,Risk 1 (High),230 W MONROE ST,2016-03-22,Canvass,Pass w/ Conditions,3. POTENTIALLY HAZARDOUS FOOD MEETS TEMPERATUR...,"(41.88075715864721, -87.6347092983425)",41.880757,-87.634709,41.8808,-87.6347,1,8
9,2.0,Restaurant,Risk 1 (High),230 W MONROE ST,2016-10-27,Canvass,Fail,3. POTENTIALLY HAZARDOUS FOOD MEETS TEMPERATUR...,"(41.88075715864721, -87.6347092983425)",41.880757,-87.634709,41.8808,-87.6347,1,9

In [7]:
df.head(20)

,License,Facility Type,Risk,Address,Inspection Date,Inspection Type,Results,Violations,Location,Latitude,Longitude,Latitude_4dp,Longitude_4dp,Restaurant_ID,Inspection_Sequence
0,2.0,Restaurant,Risk 1 (High),230 W MONROE ST,2010-06-15,Canvass,Pass,32. FOOD AND NON-FOOD CONTACT SURFACES PROPERL...,"(41.88075715864721, -87.6347092983425)",41.880757,-87.634709,41.8808,-87.6347,1,0
1,2.0,Restaurant,Risk 1 (High),230 W MONROE ST,2011-02-15,Canvass,Pass,32. FOOD AND NON-FOOD CONTACT SURFACES PROPERL...,"(41.88075715864721, -87.6347092983425)",41.880757,-87.634709,41.8808,-87.6347,1,1
2,2.0,Restaurant,Risk 1 (High),230 W MONROE ST,2012-03-19,Canvass,Pass w/ Conditions,4. SOURCE OF CROSS CONTAMINATION CONTROLLED I....,"(41.88075715864721, -87.6347092983425)",41.880757,-87.634709,41.8808,-87.6347,1,2
3,2.0,Restaurant,Risk 1 (High),230 W MONROE ST,2013-07-19,Canvass,Pass,32. FOOD AND NON-FOOD CONTACT SURFACES PROPERL...,"(41.88075715864721, -87.6347092983425)",41.880757,-87.634709,41.8808,-87.6347,1,3
4,2.0,Restaurant,Risk 1 (High),230 W MONROE ST,2014-04-18,Canvass,Pass,32. FOOD AND NON-FOOD CONTACT SURFACES PROPERL...,"(41.88075715864721, -87.6347092983425)",41.880757,-87.634709,41.8808,-87.6347,1,4
5,2.0,Restaurant,Risk 1 (High),230 W MONROE ST,2014-11-20,Canvass,Pass,31. CLEAN MULTI-USE UTENSILS AND SINGLE SERVIC...,"(41.88075715864721, -87.6347092983425)",41.880757,-87.634709,41.8808,-87.6347,1,5
6,2.0,Restaurant,Risk 1 (High),230 W MONROE ST,2015-04-21,Canvass,Pass,31. CLEAN MULTI-USE UTENSILS AND SINGLE SERVIC...,"(41.88075715864721, -87.6347092983425)",41.880757,-87.634709,41.8808,-87.6347,1,6
7,2.0,Restaurant,Risk 1 (High),230 W MONROE ST,2015-12-14,Complaint,Pass,33. FOOD AND NON-FOOD CONTACT EQUIPMENT UTENSI...,"(41.88075715864721, -87.6347092983425)",41.880757,-87.634709,41.8808,-87.6347,1,7
8,2.0,Restaurant,Risk 1 (High),230 W MONROE ST,2016-03-22,Canvass,Pass w/ Conditions,3. POTENTIALLY HAZARDOUS FOOD MEETS TEMPERATUR...,"(41.88075715864721, -87.6347092983425)",41.880757,-87.634709,41.8808,-87.6347,1,8
9,2.0,Restaurant,Risk 1 (High),230 W MONROE ST,2016-10-27,Canvass,Fail,3. POTENTIALLY HAZARDOUS FOOD MEETS TEMPERATUR...,"(41.88075715864721, -87.6347092983425)",41.880757,-87.634709,41.8808,-87.6347,1,9
10,2.0,Restaurant,Risk 1 (High),230 W MONROE ST,2016-11-04,Canvass Re-Inspection,Pass,"35. WALLS, CEILINGS, ATTACHED EQUIPMENT CONSTR...","(41.88075715864721, -87.6347092983425)",41.880757,-87.634709,41.8808,-87.6347,1,10
11,2.0,Restaurant,Risk 1 (High),230 W MONROE ST,2016-12-14,Short Form Complaint,Pass w/ Conditions,3. POTENTIALLY HAZARDOUS FOOD MEETS TEMPERATUR...,"(41.88075715864721, -87.6347092983425)",41.880757,-87.634709,41.8808,-87.6347,1,11
12,2.0,Restaurant,Risk 1 (High),230 W MONROE ST,2017-05-12,Canvass,Pass,33. FOOD AND NON-FOOD CONTACT EQUIPMENT UTENSI...,"(41.88075715864721, -87.6347092983425)",41.880757,-87.634709,41.8808,-87.6347,1,12
13,2.0,Restaurant,Risk 1 (High),230 W MONROE ST,2018-02-13,Canvass,Pass w/ Conditions,3. POTENTIALLY HAZARDOUS FOOD MEETS TEMPERATUR...,"(41.88075715864721, -87.6347092983425)",41.880757,-87.634709,41.8808,-87.6347,1,13
14,2.0,Restaurant,Risk 1 (High),230 W MONROE ST,2019-11-01,Canvass,Pass w/ Conditions,2. CITY OF CHICAGO FOOD SERVICE SANITATION CER...,"(41.88075715864721, -87.6347092983425)",41.880757,-87.634709,41.8808,-87.6347,1,14
15,9.0,Restaurant,Risk 1 (High),116 S MICHIGAN AVE,2010-07-15,Suspected Food Poisoning,Pass,32. FOOD AND NON-FOOD CONTACT SURFACES PROPERL...,"(41.88039583825962, -87.62450172159464)",41.880396,-87.624502,41.8804,-87.6245,2,0
16,9.0,Restaurant,Risk 1 (High),116 S MICHIGAN AVE,2011-06-01,Canvass,Pass,32. FOOD AND NON-FOOD CONTACT SURFACES PROPERL...,"(41.88039583825962, -87.62450172159464)",41.880396,-87.624502,41.8804,-87.6245,2,1
17,9.0,Restaurant,Risk 1 (High),116 S MICHIGAN AVE,2012-06-14,Complaint,Pass,32. FOOD AND NON-FOOD CONTACT SURFACES PROPERL...,"(41.88039583825962, -87.62450172159464)",41.880396,-87.624502,41.8804,-87.6245,2,2
18,9.0,Restaurant,Risk 1 (High),116 S MICHIGAN AVE,2013-08-22,Canvass,Pass,32. FOOD AND NON-FOOD CONTACT SURFACES PROPERL...,"(41.88039583825962, -87.62450172159464)",41.880396,-87.624502,41.8804,-87.6245,2,3
19,9.0,Restaurant,Risk 1 (High),116 S MICHIGAN AVE,2013-12-16,Canvass,Pass,33. FOOD AND NON-FOOD CONTACT EQUIPMENT UTENSI...,"(41.88039583825962, -87.62450172159464)",41.880396,-87.624502,41.8804,-87.6245,2,4

In [8]:
# Calculate the number of days since the previous inspection
df["Days_Since_Previous_Inspection"] = (
    df.groupby("Restaurant_ID")["Inspection Date"]
      .diff()
      .dt.days
)

In [9]:
df = df.drop(columns=["Facility Type"])

In [10]:
df.head(15)

,License,Risk,Address,Inspection Date,Inspection Type,Results,Violations,Location,Latitude,Longitude,Latitude_4dp,Longitude_4dp,Restaurant_ID,Inspection_Sequence,Days_Since_Previous_Inspection
0,2.0,Risk 1 (High),230 W MONROE ST,2010-06-15,Canvass,Pass,32. FOOD AND NON-FOOD CONTACT SURFACES PROPERL...,"(41.88075715864721, -87.6347092983425)",41.880757,-87.634709,41.8808,-87.6347,1,0,NaN
1,2.0,Risk 1 (High),230 W MONROE ST,2011-02-15,Canvass,Pass,32. FOOD AND NON-FOOD CONTACT SURFACES PROPERL...,"(41.88075715864721, -87.6347092983425)",41.880757,-87.634709,41.8808,-87.6347,1,1,245.0
2,2.0,Risk 1 (High),230 W MONROE ST,2012-03-19,Canvass,Pass w/ Conditions,4. SOURCE OF CROSS CONTAMINATION CONTROLLED I....,"(41.88075715864721, -87.6347092983425)",41.880757,-87.634709,41.8808,-87.6347,1,2,398.0
3,2.0,Risk 1 (High),230 W MONROE ST,2013-07-19,Canvass,Pass,32. FOOD AND NON-FOOD CONTACT SURFACES PROPERL...,"(41.88075715864721, -87.6347092983425)",41.880757,-87.634709,41.8808,-87.6347,1,3,487.0
4,2.0,Risk 1 (High),230 W MONROE ST,2014-04-18,Canvass,Pass,32. FOOD AND NON-FOOD CONTACT SURFACES PROPERL...,"(41.88075715864721, -87.6347092983425)",41.880757,-87.634709,41.8808,-87.6347,1,4,273.0
5,2.0,Risk 1 (High),230 W MONROE ST,2014-11-20,Canvass,Pass,31. CLEAN MULTI-USE UTENSILS AND SINGLE SERVIC...,"(41.88075715864721, -87.6347092983425)",41.880757,-87.634709,41.8808,-87.6347,1,5,216.0
6,2.0,Risk 1 (High),230 W MONROE ST,2015-04-21,Canvass,Pass,31. CLEAN MULTI-USE UTENSILS AND SINGLE SERVIC...,"(41.88075715864721, -87.6347092983425)",41.880757,-87.634709,41.8808,-87.6347,1,6,152.0
7,2.0,Risk 1 (High),230 W MONROE ST,2015-12-14,Complaint,Pass,33. FOOD AND NON-FOOD CONTACT EQUIPMENT UTENSI...,"(41.88075715864721, -87.6347092983425)",41.880757,-87.634709,41.8808,-87.6347,1,7,237.0
8,2.0,Risk 1 (High),230 W MONROE ST,2016-03-22,Canvass,Pass w/ Conditions,3. POTENTIALLY HAZARDOUS FOOD MEETS TEMPERATUR...,"(41.88075715864721, -87.6347092983425)",41.880757,-87.634709,41.8808,-87.6347,1,8,99.0
9,2.0,Risk 1 (High),230 W MONROE ST,2016-10-27,Canvass,Fail,3. POTENTIALLY HAZARDOUS FOOD MEETS TEMPERATUR...,"(41.88075715864721, -87.6347092983425)",41.880757,-87.634709,41.8808,-87.6347,1,9,219.0
10,2.0,Risk 1 (High),230 W MONROE ST,2016-11-04,Canvass Re-Inspection,Pass,"35. WALLS, CEILINGS, ATTACHED EQUIPMENT CONSTR...","(41.88075715864721, -87.6347092983425)",41.880757,-87.634709,41.8808,-87.6347,1,10,8.0
11,2.0,Risk 1 (High),230 W MONROE ST,2016-12-14,Short Form Complaint,Pass w/ Conditions,3. POTENTIALLY HAZARDOUS FOOD MEETS TEMPERATUR...,"(41.88075715864721, -87.6347092983425)",41.880757,-87.634709,41.8808,-87.6347,1,11,40.0
12,2.0,Risk 1 (High),230 W MONROE ST,2017-05-12,Canvass,Pass,33. FOOD AND NON-FOOD CONTACT EQUIPMENT UTENSI...,"(41.88075715864721, -87.6347092983425)",41.880757,-87.634709,41.8808,-87.6347,1,12,149.0
13,2.0,Risk 1 (High),230 W MONROE ST,2018-02-13,Canvass,Pass w/ Conditions,3. POTENTIALLY HAZARDOUS FOOD MEETS TEMPERATUR...,"(41.88075715864721, -87.6347092983425)",41.880757,-87.634709,41.8808,-87.6347,1,13,277.0
14,2.0,Risk 1 (High),230 W MONROE ST,2019-11-01,Canvass,Pass w/ Conditions,2. CITY OF CHICAGO FOOD SERVICE SANITATION CER...,"(41.88075715864721, -87.6347092983425)",41.880757,-87.634709,41.8808,-87.6347,1,14,626.0

In [11]:
df = df.drop(
    columns=["Address", "Latitude_4dp","Longitude_4dp", "Latitude", "Longitude","License"]
)

In [12]:
# OUTPUT_PATH = "../data/processed/restaurant_identity_added_feature.csv"

# df.to_csv(
#     OUTPUT_PATH,
#     index=False
# )

# print("File saved successfully!")
# print("Saved to:", OUTPUT_PATH)

In [13]:
df['Results'].value_counts()

Results
Pass                  84213
Fail                  37666
Pass w/ Conditions    34450
No Entry                581
Not Ready                44
Out of Business          31
Name: count, dtype: int64